import {run,test,assert} from './harness.js';
import './monitoring.test.js';
import './native.test.js';
import './databases.test.js';
import './workspace.test.js';
import './board.test.js';
import './chart-layout.test.js';
import './chart-scale.test.js';
import './chart-interface.test.js';
import './dashboard-controls.test.js';
import './chart-family.test.js';
import './integrations.test.js';
import './operations.test.js';
import {esc} from '/assets/ui.js';
import {scopeSnapshot} from '/assets/lib/assets.js';
import {ruleState} from '/assets/lib/rule-catalog.js';
test('a fresh null sample is still missing rule evidence in a single infrastructure scope',()=>{const snapshot={end:100,assets:[{id:'a',enabled:true}],metrics:[{id:'p99',state:'ok',latest:null,series:[{labels:{assetId:'a'},points:[{time:100,value:null}]}]}],targets:[],connected:true,mode:'test'};const scoped=scopeSnapshot(snapshot,'a');assert.equal(scoped.metrics[0].state,'stale');assert.equal(ruleState({id:'r',requiredIds:['p99']},scoped,[]),'missing')});
test('untrusted infrastructure names cannot become markup',()=>{const node=document.createElement('div');node.innerHTML=esc('<img src=x onerror=alert(1)>"\'&');assert.equal(node.children.length,0);assert.equal(node.textContent,'<img src=x onerror=alert(1)>"\'&')});
test('module worker announces readiness before the first real snapshot request',()=>new Promise((resolve,reject)=>{const worker=new Worker('/assets/worker.js',{type:'module'});const finish=error=>{clearTimeout(timer);worker.terminate();error?reject(error):resolve()};const timer=setTimeout(()=>finish(new Error('worker startup timeout')),15000);worker.onerror=()=>finish(new Error('worker failed'));worker.onmessage=({data})=>{if(data.type==='ready')worker.postMessage({type:'load',range:900});else if(data.type==='snapshot'){try{assert.equal(data.snapshot.metrics.length,123);assert.ok(Array.isArray(data.incidents));finish()}catch(e){finish(e)}}else if(data.type==='error')finish(new Error(data.message))}}));
await run();
