import {$,$$,esc,dialog,request,fullTime} from './ui.js';

export const aiStatusLabels={queued:'배정 대기',routing:'Jev 분석 중',ready:'실행 대기',running:'작업 중',review:'담당 확인 필요',blocked:'실행 환경 확인',completed:'응답 완료 · 결과 검토',failed:'실행 실패',cancelled:'취소됨',interrupted:'중단됨'};
export const aiCategoryLabels={implementation:'기능 구현',debugging:'오류 수정',testing:'테스트',design:'화면·경험 설계',review:'검토',documentation:'문서·설명',other:'기타'};
const names={codex:'Codex',claude:'Claude',review:'직접 확인'};
const message=(root,text)=>{const node=$('[data-ai-notice]',root);if(node)node.textContent=text};
const percent=n=>Number.isFinite(n)?Math.round(n*100)+'%':'미제공';
const usageHTML=j=>j.usageReported?`입력 ${Number(j.inputTokens)||0} · 출력 ${Number(j.outputTokens)||0} 토큰`:'토큰 사용량 미제공';
const decisionHTML=d=>`<div class="ai-decision"><strong>${esc(names[d.provider]||d.provider)} · ${esc(aiCategoryLabels[d.category]||d.category)}</strong><span>Jev 확신도 ${percent(d.confidence)}</span><p>${esc(d.basis)}</p><p>${Object.entries(d.probabilities).map(([name,p])=>`${esc(names[name]||name)} ${percent(p)}`).join(' · ')}</p><small>${esc(d.model)} · 입력 ${Number(d.inputTokens)||0} 토큰</small>${d.needsReview?'<p>자동 실행을 보류했습니다. 요청을 보완하거나 담당을 직접 선택하세요.</p>':''}</div>`;
export function aiSettingsInput(form,settings){
 const data={version:settings.version,model:form.elements.jevModel.value.trim(),threshold:Number(form.elements.threshold.value)/100,concurrency:Number(form.elements.concurrency.value),timeoutMinutes:Number(form.elements.timeoutMinutes.value),profiles:{}};
 for(const id of ['codex','claude'])data.profiles[id]={enabled:form.elements[id+'Enabled'].checked,model:form.elements[id+'Model'].value.trim(),strengths:form.elements[id+'Strengths'].value.trim()};
 if(form.elements.apiKey.value.trim()||form.dataset.clearKey==='true')data.apiKey=form.elements.apiKey.value.trim();return data;
}
export async function mountAISettings(root,api=request){
 root.innerHTML='<h2>Jev 자동 작업 배정</h2><p data-ai-notice role="status">설정을 불러오고 있습니다…</p>';
 try{
  const {settings:s,runtime,root:projectRoot}=await api('ai/settings');if(!root.isConnected)return;
  root.innerHTML=`<header class="integration-heading"><div><h2>Jev 자동 작업 배정</h2><p>프롬프트·프로젝트 문맥·담당 기준·사용자 평가를 함께 보고 실행 대상을 고릅니다.</p></div><a class="filter-button" href="#ai">AI 작업으로 이동</a></header><form class="ops-form ai-settings-form"><div class="field-grid"><label>Jev 모델<input name="jevModel" required maxlength="120" value="${esc(s.model)}"></label><label>Jev API 키<input name="apiKey" type="password" autocomplete="new-password" placeholder="${s.hasKey?'저장된 키 유지 · 변경할 때만 입력':'TypeSafe API 키'}"></label></div>${s.hasKey?'<button type="button" class="plain-link" data-clear-key>저장된 키 삭제</button>':''}<p class="modal-footnote">키는 암호화해 저장합니다. 분석할 프롬프트와 프로젝트 설명·평가가 TypeSafe API로 전송됩니다.</p><div class="field-grid"><label>자동 배정 최소 확신도 (%)<input name="threshold" type="number" min="0" max="100" value="${Math.round(s.threshold*100)}" required></label><label>동시 실행 수<select name="concurrency">${[1,2,3,4].map(n=>`<option value="${n}" ${s.concurrency===n?'selected':''}>${n}개</option>`).join('')}</select></label><label>작업 시간 제한 (분)<input name="timeoutMinutes" type="number" min="1" max="120" value="${s.timeoutMinutes}" required></label></div><p class="editor-help">담당 기준의 기본값은 시작을 위한 예시입니다. 모델별 성능을 측정한 결과는 아닙니다. 같은 프로젝트의 완료 작업에 남긴 평가를 이후 배정에 참고합니다.</p><div class="ai-profile-grid">${['codex','claude'].map(id=>`<fieldset><legend>${names[id]} <span class="health-label ${runtime[id]?'connected':'paused'}">${runtime[id]?'실행 도구 있음':'설치 확인 필요'}</span></legend><label class="check-field"><input name="${id}Enabled" type="checkbox" ${s.profiles[id].enabled?'checked':''}>배정 대상으로 사용</label><label>실행 모델 (선택)<input name="${id}Model" value="${esc(s.profiles[id].model)}" maxlength="120" placeholder="비우면 설치된 도구의 기본 모델"></label><label>잘하는 일 · 프로젝트별 선호<textarea name="${id}Strengths" rows="4" maxlength="4000" required>${esc(s.profiles[id].strengths)}</textarea></label></fieldset>`).join('')}</div><p class="modal-footnote">프로젝트 상위 폴더: ${esc(projectRoot||'서버에 PULSE_AI_PROJECT_ROOT 설정 필요')}<br>실행 도구의 존재를 확인한 표시입니다. 로그인과 모델 접근 권한은 실제 실행 때 확인합니다.</p><p data-ai-notice role="status"></p><button class="primary-button" type="submit">자동 배정 설정 저장</button></form>`;
  const form=$('form',root);$('[data-clear-key]',root)?.addEventListener('click',e=>{form.dataset.clearKey='true';form.elements.apiKey.value='';e.target.textContent='저장 시 키 삭제'});
  form.onsubmit=async e=>{e.preventDefault();const b=$('[type=submit]',form);b.disabled=true;try{await api('ai/settings','PUT',aiSettingsInput(form,s));await mountAISettings(root,api);message(root,'설정을 저장했습니다')}catch(e){message(root,e.message)}finally{b.disabled=false}};
 }catch(e){message(root,e.message)}
}
export function openAIProject(onSaved,api=request){
 const d=dialog('작업 프로젝트 등록','이 서버에서 접근할 수 있는 Git 저장소를 연결합니다.',`<form class="ops-form"><label>프로젝트 이름<input name="name" required maxlength="120" placeholder="예: ticketing-platform"></label><label>프로젝트 폴더<input name="directory" required placeholder="예: /home/user/projects/ticketing-platform"></label><label>프로젝트 설명 · 작업 기준<textarea name="context" rows="4" maxlength="8000" placeholder="사용 기술, 자주 하는 작업, 완료 기준 등을 적어주세요"></textarea></label><p class="modal-footnote">커밋된 파일을 별도 작업 공간으로 가져옵니다. 원래 폴더의 저장하지 않은 변경은 작업에 포함되지 않습니다.</p><p data-ai-notice role="alert"></p><button type="submit" class="primary-button">프로젝트 등록</button></form>`);
 $('form',d).onsubmit=async e=>{e.preventDefault();const f=e.target,b=$('[type=submit]',f);b.disabled=true;try{await api('ai/projects','POST',{name:f.elements.name.value.trim(),directory:f.elements.directory.value.trim(),context:f.elements.context.value.trim()});d.close();await onSaved()}catch(e){message(d,e.message)}finally{b.disabled=false}};return d;
}
export async function openAIJob(id,onChanged=()=>{},api=request){
 const d=dialog('AI 작업 상세','',`<p data-ai-notice role="status">작업을 불러오고 있습니다…</p><div data-ai-detail></div>`,{className:'wide-dialog'});let j;
 const action=async(action,extra={})=>{try{j=await api(`ai/jobs/${id}/action`,'POST',{version:j.version,action,...extra});await load();await onChanged()}catch(e){message(d,e.message)}};
 const load=async()=>{try{j=await api('ai/jobs/'+id);if(!d.isConnected)return;message(d,'');const ended=['completed','failed','cancelled','interrupted'].includes(j.status);$('[data-ai-detail]',d).innerHTML=`<div class="ai-job-meta"><strong>${esc(aiStatusLabels[j.status]||j.status)}</strong><span>${esc(names[j.provider]||'담당 미정')} · ${esc(fullTime(j.createdAt))}</span></div><pre class="ops-preview">${esc(j.prompt)}</pre>${j.decision?decisionHTML(j.decision):''}${j.error?`<p class="integration-error">${esc(j.error)}</p>`:''}<div class="row-actions"><button class="filter-button" data-reload>결과 새로고침</button>${!ended?'<button class="filter-button" data-cancel-job>작업 취소</button>':''}${['review','blocked'].includes(j.status)?'<button class="filter-button" data-assign="codex">Codex에 배정</button><button class="filter-button" data-assign="claude">Claude에 배정</button>':''}${['failed','cancelled','interrupted','blocked'].includes(j.status)?'<button class="filter-button" data-retry-job>새 작업 공간에서 재시도</button>':''}</div>${j.output?`<h3>실행 응답</h3><pre class="ops-preview ai-output">${esc(j.output)}</pre>`:''}${j.status==='completed'?`<p class="modal-footnote">에이전트 응답이 완료된 상태입니다. 테스트 통과나 변경 승인 여부는 실행 응답에서 확인하세요.</p><div class="row-actions"><button class="filter-button" data-rate="good" aria-pressed="${j.rating==='good'}">결과 만족</button><button class="filter-button" data-rate="needs_work" aria-pressed="${j.rating==='needs_work'}">보완 필요</button></div>`:''}${j.workspace?`<details class="source-detail"><summary>작업 공간과 실행 기록</summary><p>작업 폴더 <code>${esc(j.workspace)}</code></p><p>작업 브랜치 <code>${esc(j.branch)}</code></p><p>기준 커밋 <code>${esc(j.baseCommit)}</code></p><p>세션 ${esc(j.sessionId||'미제공')} · 모델 ${esc(j.model||'실행 도구 기본값')}</p><p>${usageHTML(j)}</p></details>`:''}`;
  $('[data-reload]',d).onclick=load;$('[data-cancel-job]',d)?.addEventListener('click',()=>action('cancel'));$('[data-retry-job]',d)?.addEventListener('click',()=>action('retry'));$$('[data-assign]',d).forEach(b=>b.onclick=()=>action('assign',{provider:b.dataset.assign}));$$('[data-rate]',d).forEach(b=>b.onclick=()=>action('rate',{rating:b.dataset.rate}));
 }catch(e){message(d,e.message)}};await load();return d;
}
export async function mountAITasks(root,api=request){
 let stopped=false,timer;const stop=()=>{stopped=true;clearTimeout(timer)};
 root.innerHTML=`<header class="integration-heading"><div><h1>AI 작업</h1><p>프롬프트를 등록하면 Jev가 담당을 고르고 독립 작업 공간에서 실행합니다.</p></div><a class="filter-button" href="#settings">배정 설정</a></header><section class="settings-card"><form class="ops-form" data-ai-task><div class="field-grid"><label>작업 프로젝트<select name="projectId" required aria-label="작업 프로젝트"><option value="">프로젝트를 불러오는 중…</option></select></label><div class="ai-add-project"><button type="button" class="filter-button" data-add-project>프로젝트 등록</button></div></div><label>맡길 일<textarea name="prompt" rows="5" required maxlength="16000" placeholder="원하는 결과와 완료 기준을 적어주세요. 예: 결제 요청이 중복되는 원인을 찾아 수정하고 재현 테스트를 추가해줘."></textarea></label><p class="modal-footnote">자동 배정은 저장한 담당 기준과 사용자 평가를 참고합니다. 확신도가 낮으면 담당 확인을 기다립니다. 각 작업은 별도 세션·브랜치로 실행되며 결과를 검토할 수 있습니다.</p><div class="row-actions"><button type="button" class="filter-button" data-preview>배정만 미리보기</button><button type="submit" class="primary-button">Jev 자동 배정 · 실행</button></div><p data-ai-notice role="status"></p><div data-ai-preview></div></form></section><section class="settings-card"><header class="integration-heading"><h2>작업 진행</h2><button class="filter-button" data-reload-jobs>목록 새로고침</button></header><p role="status" data-list-notice></p><div data-ai-jobs></div></section>`;
 const form=$('[data-ai-task]',root);let projects=[];
 const loadProjects=async()=>{projects=await api('ai/projects');if(stopped||!form.isConnected)return;const select=form.elements.projectId,selected=select.value;select.innerHTML='<option value="">프로젝트 선택</option>'+projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');select.value=projects.some(p=>p.id===selected)?selected:projects.length===1?projects[0].id:''};
 const loadJobs=async()=>{try{const jobs=await api('ai/jobs');if(stopped||!form.isConnected)return;$('[data-list-notice]',root).textContent='';$('[data-ai-jobs]',root).innerHTML=jobs.length?jobs.map(j=>`<button class="ai-job-row" data-job="${esc(j.id)}"><div><strong>${esc(j.prompt.slice(0,100))}</strong><small>${esc(projects.find(p=>p.id===j.projectId)?.name||'프로젝트')} · ${esc(names[j.provider]||'배정 대기')} · ${esc(fullTime(j.createdAt))}</small></div><span class="health-label ${j.status==='completed'?'connected':j.status==='running'?'pending':['failed','blocked','interrupted'].includes(j.status)?'warning':'paused'}">${esc(aiStatusLabels[j.status]||j.status)}</span></button>`).join(''):'<p class="muted-text">등록한 작업이 없습니다. 첫 프롬프트를 맡겨보세요.</p>';$$('[data-job]',root).forEach(b=>b.onclick=()=>openAIJob(b.dataset.job,loadJobs,api))}catch(e){if(form.isConnected)$('[data-list-notice]',root).textContent=e.message}};
 const input=()=>({projectId:form.elements.projectId.value,prompt:form.elements.prompt.value.trim()});
 const submit=async preview=>{if(!form.reportValidity())return;$$('button',form).forEach(b=>b.disabled=true);message(root,preview?'Jev가 배정을 분석하고 있습니다…':'작업을 등록하고 있습니다…');try{const v=await api(preview?'ai/preview':'ai/jobs','POST',input());if(stopped||!form.isConnected)return;if(preview){$('[data-ai-preview]',root).innerHTML=decisionHTML(v);message(root,'배정 판단만 확인했습니다. 작업을 실행하지 않았습니다.')}else{form.elements.prompt.value='';$('[data-ai-preview]',root).textContent='';message(root,'작업을 등록했습니다. 아래 목록에서 진행 상황을 확인하세요.');await loadJobs()}}catch(e){message(root,e.message)}finally{$$('button',form).forEach(b=>b.disabled=false)}};
 form.onsubmit=e=>{e.preventDefault();void submit(false)};$('[data-preview]',root).onclick=()=>submit(true);$('[data-add-project]',root).onclick=()=>openAIProject(loadProjects,api);$('[data-reload-jobs]',root).onclick=loadJobs;
 const poll=async()=>{if(stopped||!form.isConnected){stop();return}if(!document.hidden)await loadJobs();if(!stopped)timer=setTimeout(poll,3000)};
 try{await loadProjects();await loadJobs();if(!stopped)timer=setTimeout(poll,3000)}catch(e){message(root,e.message)}return stop;
}
