import {metrics,metricById} from './lib/catalog.js';
import {assetLabels,statusLabels,scopeSnapshot,registeredIncidents} from './lib/assets.js';
import {eventRules,ruleState,ruleById} from './lib/rule-catalog.js';
import {groupEvents,relatedAssets,eventMetricIds,metricsForAsset,observedForAsset,comparisonLines,boardSelection,metricRecipes as recipesForMetrics,dashboardRecipes,unselectedServers,withDockerHosts} from './lib/board.js';
import {buildAction} from './lib/deploy.js';
import {infrastructurePicker,bindInfrastructurePicker} from './lib/dashboard-controls.js';
import {enter} from './lib/motion.js';
import {mountIntegrations} from './integrations.js';
import {mountMutes,mountDeliveries,mountEventHistory,mountViews,openGlobalSearch,openDiagnostic,openCSVImport,bindBulkInfrastructure,assetSearchText} from './operations.js';
import {ChartGrid,nextRefreshSeconds,chartInteractionActive,updateAllCharts} from './charts.js';
import {$,$$,esc,icon,infraIcon,fullTime,clockTime,dialog,request,preference,savePreference,debounce,download} from './ui.js';

const pages={dashboard:'대시보드',infrastructure:'인프라 관리',events:'이벤트',settings:'환경설정'};
const board=preference('pulse-dashboard-board-v1',{}),display=preference('pulse-display-preferences',{});
let snapshot,incidents=[],page=pages[location.hash.slice(1).split('?')[0]]?location.hash.slice(1).split('?')[0]:'dashboard',grids=[],focusEvent=new URLSearchParams(location.hash.split('?')[1]||'').get('rule'),selection=board.selectedIds??board.ids??board.selection;
let search='',animateCharts=false,ruleSearch='',rulePage=0,ruleAsset='all',ruleOpen=null,eventTab='active',eventFilter='all',refreshSeconds=[0,15,30,60].includes(display.refreshSeconds)?display.refreshSeconds:30,timer,layoutKey='',detailUpdate,forceNext=false;
const main=$('#main'),worker=new Worker('/assets/worker.js',{type:'module'});
const pill=(value,label)=>`<span class="health-label ${esc(value)}">${esc(label||statusLabels[value]||value)}</span>`;
const empty=message=>`<div class="empty-state">${esc(message)}</div>`;
const pageHeading=(eyebrow,title,description,actions='')=>`<div class="page-heading"><div>${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h1 class="sr-only">${title}</h1>${description?`<p>${description}</p>`:''}</div><div class="heading-actions">${actions}</div></div>`;
// Registered infrastructure only; derived Docker hosts appear on graphs and events, not in management.
const assets=()=>(snapshot?.assets||[]).filter(a=>!a.virtual);
const currentSelection=()=>boardSelection(selection,assets());
const persist=()=>savePreference('pulse-dashboard-board-v1',{selectedIds:currentSelection()});
function notify(message){const n=$('#notice');n.textContent=message;n.hidden=!message}
function refresh(force=true){forceNext=forceNext||force;clearTimeout(timer);$('#refresh').classList.add('busy');worker.postMessage({type:'load',range:Number($('#time-range').value)})}
function schedule(){clearTimeout(timer);const seconds=nextRefreshSeconds(refreshSeconds);if(seconds&&!document.hidden)timer=setTimeout(()=>refresh(false),seconds*1000)}

function metricRecipes(ids,definitions){return recipesForMetrics(snapshot,ids,definitions)}
function mountCharts(root,recipes,list=grids,onDetail=openMetric){if(!recipes.length){root.innerHTML=empty('관측값 없음');return}const grid=new ChartGrid(root,recipes,snapshot,onDetail,animateCharts);list.push(grid)}
function clearGrids(){grids.forEach(g=>g.destroy());grids=[]}
function openMetric(metric,ids){let captured=snapshot;let local=[];const d=dialog(metric.title,metric.description||'관측 지표 상세',`<div class="metric-facts"><span>단위 <b>${esc(metric.unit)}</b></span><span>기준 <b>${metric.warning??'없음'} ${esc(metric.unit)}</b></span></div>${metric.interpretation||metric.meaning?`<p class="muted-text">${esc(metric.interpretation||metric.meaning)}</p>`:''}<div class="board-chart-grid"></div><details class="source-detail"><summary>계측 참고식</summary><pre>${esc(metric.query||'직접 수집')}</pre></details><button class="filter-button" data-export>이 지표 JSON 내려받기</button>`,{className:'metric-dialog',onClose:()=>{local.forEach(g=>g.destroy());detailUpdate=null}});mountCharts($('.board-chart-grid',d),metricRecipes(ids,[metric]),local,null);detailUpdate=()=>{captured=snapshot};$('[data-export]',d).onclick=()=>download(`${metric.id}.json`,{start:captured.start,end:captured.end,metric,series:comparisonLines(captured,ids,[metric.id])})}
async function edit(asset={}){const {openEditor}=await import('./editor.js');openEditor(asset,assets(),()=>{layoutKey='';refresh()})}
async function candidates(){const {openCandidates}=await import('./editor.js');openCandidates(assets(),()=>{layoutKey='';refresh()})}
async function terminal(asset){const {openTerminal}=await import('./terminal.js');openTerminal(asset)}
async function assetAction(id,action,button){button.disabled=true;try{await request(`assets/${id}/${action}`,'POST');layoutKey='';refresh()}catch(e){notify(e.message)}finally{button.disabled=false}}
function showAsset(asset){const local=[];const relevant=incidents.filter(i=>i.assetId===asset.id);const d=dialog(asset.name,`${assetLabels[asset.kind]} · ${asset.address||'주소 미입력'}`,`<div class="detail-actions">${pill(asset.status)}<button class="filter-button" data-focus>대시보드에서 보기</button><button class="filter-button" data-edit>연결 정보</button><button class="filter-button" data-terminal>터미널</button><button class="filter-button" data-diagnose>연결 진단</button></div>${relevant.length?`<div class="detail-events">${relevant.map(i=>`<button class="event-line" data-event="${esc(i.ruleId)}">${pill(i.severity,i.status==='pending'?'지속 시간 확인 중':'발생')}<strong>${esc(i.title)}</strong><span>${esc(i.value)} ${esc(i.unit)}</span>${icon('arrow')}</button>`).join('')}</div>`:''}${asset.message?`<p class="muted-text">${esc(asset.message)}</p>`:''}<div class="board-chart-grid"></div>`,{className:'wide-dialog',onClose:()=>{local.forEach(g=>g.destroy());detailUpdate=null}});mountCharts($('.board-chart-grid',d),metricRecipes([asset.id],metricsForAsset(snapshot,asset).filter(m=>observedForAsset(snapshot,m.id,asset.id))),local);detailUpdate=()=>{const live=snapshot.assets.find(a=>a.id===asset.id);if(live){const badge=$('.detail-actions>.health-label',d);badge.className='health-label '+live.status;badge.textContent=statusLabels[live.status]||live.status}$$('[data-event]',d).forEach(button=>{const current=incidents.find(i=>i.assetId===asset.id&&i.ruleId===button.dataset.event);button.hidden=!current;if(current)button.querySelector('span:nth-last-child(2)').textContent=current.value+' '+current.unit})};$('[data-focus]',d).onclick=()=>{d.close();selection=[asset.id];persist();navigate('dashboard')};$('[data-edit]',d).onclick=()=>edit(asset);$('[data-terminal]',d).onclick=()=>terminal(asset);$('[data-diagnose]',d).onclick=()=>openDiagnostic(asset);$$('[data-event]',d).forEach(b=>b.onclick=()=>{focusEvent=b.dataset.event;d.close();openEvent(focusEvent)})}
function bindAssets(root=main){$$('[data-edit]',root).forEach(b=>b.onclick=()=>edit(assets().find(a=>a.id===b.dataset.edit)));$$('[data-asset]',root).forEach(b=>b.onclick=()=>showAsset(assets().find(a=>a.id===b.dataset.asset)));$$('[data-terminal]',root).forEach(b=>b.onclick=()=>terminal(assets().find(a=>a.id===b.dataset.terminal)));$$('[data-action]',root).forEach(b=>b.onclick=()=>assetAction(b.dataset.id,b.dataset.action,b));$$('[data-add]',root).forEach(b=>b.onclick=()=>edit());$$('[data-candidates]',root).forEach(b=>b.onclick=candidates)}
function assetNames(ids){const names=ids.map(id=>snapshot?.assets?.find(a=>a.id===id)?.name).filter(Boolean);return names.slice(0,2).join(' · ')+(names.length>2?` 외 ${names.length-2}개`:'')}
function openEvent(id){focusEvent=id;eventTab='active';if(page==='events')render(true);else navigate('events')}
function renderDashboard(){
 const ids=currentSelection(),shown=withDockerHosts(snapshot.assets,ids),groups=groupEvents(incidents.filter(i=>!i.assetId||shown.includes(i.assetId))),missing=unselectedServers(assets(),ids);
 main.innerHTML=`<h1 class="sr-only">대시보드</h1><div id="saved-views" class="saved-views"></div><div class="monitoring-board">
 ${infrastructurePicker(assets(),ids,search)}
 ${groups.length?`<div class="dashboard-alerts">${groups.map(g=>`<button class="dashboard-alert ${esc(g.severity)}" data-event="${esc(g.id)}">${pill(g.severity,g.incidents.every(i=>i.status==='pending')?'확인 중':g.severity==='critical'?'긴급':g.severity==='warning'?'주의':'안내')}<strong>${esc(g.title)}</strong><span>${esc(assetNames(g.assetIds))}</span>${icon('arrow',14)}</button>`).join('')}</div>`:''}
 ${missing.length?`<div class="resource-hint">${icon('server')}<span>맨 위 기본 리소스의 디스크와 서버 CPU·RAM은 서버 지표입니다. 지금 선택에는 서버가 없습니다.</span><button class="filter-button" data-add-servers>서버 ${missing.length}대 함께 보기</button></div>`:''}
 <div class="board-chart-grid" id="all-charts">${ids.length?'':empty('인프라를 선택하세요.')}</div></div>`;
 $$('[data-event]',main).forEach(b=>b.onclick=()=>openEvent(b.dataset.event));
 bindInfrastructurePicker(main,assets(),currentSelection,ids=>{selection=ids;persist();render(true)},query=>search=query);
 $('[data-add-servers]',main)?.addEventListener('click',()=>{selection=[...new Set([...currentSelection(),...missing.map(a=>a.id)])];persist();render(true)});
 if(ids.length)mountCharts($('#all-charts'),dashboardRecipes(snapshot,shown));
 void mountViews($('#saved-views'),()=>({assetIds:currentSelection(),range:Number($('#time-range').value),refreshSeconds}),applyView);
}

function applyView(view){selection=view.assetIds.filter(id=>assets().some(a=>a.id===id));persist();$('#time-range').value=String(view.range);refreshSeconds=view.refreshSeconds;savePreference('pulse-display-preferences',{...display,refreshSeconds});layoutKey='';if(page!=='dashboard')navigate('dashboard');else render(true);refresh()}
function renderEventFocus(group){
 const root=$('#event-detail');if(!group||!root)return;
 const related=relatedAssets(snapshot,group.assetIds),ids=related.map(a=>a.id),rule=ruleById.get(group.id);
 root.innerHTML=`<div class="board-event-focus"><header><div><h3>${esc(group.title)}</h3><p>${esc(rule?.condition||group.incidents[0]?.summary)} · ${esc(rule?.duration||'')}</p></div><button class="icon-button" aria-label="이벤트 상세 닫기">${icon('close')}</button></header><div class="board-related">${related.map(a=>`<span class="${group.assetIds.includes(a.id)?'affected':''}">${esc(a.name)}<small>${group.assetIds.includes(a.id)?'발생 대상':'연결 인프라'}</small></span>`).join('')}</div><div class="board-event-evidence">${group.incidents.map(i=>`<div><strong>${esc(i.scope)}</strong><span>${esc(i.value)} ${esc(i.unit)}</span><small>${esc(i.evidence.join(' · '))}</small></div>`).join('')}</div><div class="board-chart-grid"></div><footer><p>${esc([...new Set(group.incidents.flatMap(i=>i.steps))].join(' → '))}</p><button class="filter-button" data-compare-event>대시보드에서 보기</button></footer></div>`;
 $('header button',root).onclick=()=>{focusEvent=null;render(true)};
 $('[data-compare-event]',root).onclick=()=>{selection=ids;persist();navigate('dashboard')};
 const definitions=eventMetricIds(group,related).map(id=>metricById.get(id)).filter(m=>m&&ids.some(id=>observedForAsset(snapshot,m.id,id)));
 mountCharts($('.board-chart-grid',root),metricRecipes(ids,definitions));
}
function renderInfrastructure(){main.innerHTML=pageHeading('','인프라 관리','',`<button class="filter-button" data-candidates>SSH 연결 후보</button><button class="filter-button" data-csv-import>CSV 일괄 등록</button><button class="primary-button" data-add>${icon('plus')} 인프라 등록</button>`)+`<div class="toolbar"><label class="search-field">${icon('search')}<input id="inventory-search" placeholder="이름 · 주소 · 환경 · 태그 검색" aria-label="인프라 목록 검색"></label><span data-selection-count></span><button class="filter-button" data-bulk="connect">선택 연결 시작</button><button class="filter-button" data-bulk="pause">선택 일시정지</button><button class="filter-button" data-bulk="update">공통 설정</button></div><div class="table-wrap"><table class="infra-table"><thead><tr><th><input type="checkbox" data-select-all aria-label="표시된 인프라 전체 선택"></th><th>인프라</th><th>연결 주소</th><th>수집 상태</th><th>관리</th></tr></thead><tbody>${assets().map(a=>`<tr data-row="${esc(a.id)}"><td><input type="checkbox" data-select-asset value="${esc(a.id)}" aria-label="${esc(a.name)} 선택"></td><td><button class="infra-name" data-asset="${esc(a.id)}">${infraIcon(a.kind)}<span><strong>${esc(a.name)}</strong><small>${esc(a.environment||assetLabels[a.kind])}${a.tags?.length?' · '+esc(a.tags.join(', ')):''}</small></span></button></td><td><code>${esc(a.address||'미입력')}${a.port?':'+a.port:''}</code>${a.status==='error'?`<small class="row-message">${esc(a.message||'')}</small>`:''}</td><td><span data-last-seen title="${esc(a.lastSeen?fullTime(a.lastSeen):'관측 전')}">${pill(a.status)}</span></td><td><div class="row-actions"><button class="icon-button" data-edit="${esc(a.id)}" aria-label="${esc(a.name)} 연결 정보">${icon('edit')}</button><button class="icon-button" data-terminal="${esc(a.id)}" aria-label="${esc(a.name)} 터미널">${icon('terminal')}</button><button class="filter-button" data-id="${esc(a.id)}" data-action="${a.enabled?'pause':'connect'}">${a.enabled?'일시정지':'연결 시작'}</button></div></td></tr>`).join('')}</tbody></table>${!assets().length?empty('아직 등록한 인프라가 없습니다.'):''}</div>`;bindAssets();bindBulkInfrastructure(main,assets(),()=>{layoutKey='';refresh()});$('[data-csv-import]').onclick=()=>openCSVImport(()=>{layoutKey='';refresh()});$('#inventory-search').oninput=e=>$$('[data-row]').forEach(row=>{const a=assets().find(a=>a.id===row.dataset.row);row.hidden=!assetSearchText(a).includes(e.target.value.toLowerCase())})}
function renderEvents(){main.innerHTML=pageHeading('','이벤트','')+`<div class="tabs"><button data-tab="rules" aria-pressed="${eventTab==='rules'}">이벤트 규칙 <small>${eventRules.length}</small></button><button data-tab="active" aria-pressed="${eventTab==='active'}">현재 이벤트 <small>${incidents.length}</small></button><button data-tab="history" aria-pressed="${eventTab==='history'}">처리 이력</button><button data-tab="deliveries" aria-pressed="${eventTab==='deliveries'}">알림 전송 이력</button><button data-tab="audit" aria-pressed="${eventTab==='audit'}">연결·수집 기록</button></div><div id="event-list"></div>`;$$('[data-tab]').forEach(b=>b.onclick=()=>{eventTab=b.dataset.tab;ruleOpen=null;render()});const root=$('#event-list');
 if(eventTab==='history'){void mountEventHistory(root);return}if(eventTab==='deliveries'){void mountDeliveries(root);return}if(eventTab==='audit'){loadAudit(root);return}if(eventTab==='active'){const groups=groupEvents(incidents);root.innerHTML=(groups.map(g=>`<button class="event-line" data-active="${esc(g.id)}" aria-expanded="${focusEvent===g.id}">${pill(g.severity,g.incidents.every(i=>i.status==='pending')?'확인 중':'발생')}<div><strong>${esc(g.title)}</strong><small>${esc(assetNames(g.assetIds))}</small></div>${icon('arrow')}</button>`).join('')||empty('현재 이벤트 없음'))+'<div id="event-detail"></div>';$$('[data-active]',root).forEach(b=>b.onclick=()=>{focusEvent=focusEvent===b.dataset.active?null:b.dataset.active;render(true)});renderEventFocus(groups.find(g=>g.id===focusEvent));return}
 root.innerHTML=`<div class="toolbar"><label class="search-field">${icon('search')}<input id="rule-search" aria-label="이벤트 규칙 검색" placeholder="규칙 · 발생 조건 검색" value="${esc(ruleSearch)}"></label><select id="rule-asset" aria-label="규칙 대상 인프라"><option value="all">전체 인프라</option>${assets().map(a=>`<option value="${esc(a.id)}" ${ruleAsset===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select><select id="rule-filter" aria-label="규칙 상태"><option value="all">모든 상태</option><option value="firing">발생</option><option value="pending">확인 중</option><option value="missing">관측 필요</option><option value="waiting">조건 감시 중</option></select></div><div id="rule-table"></div>`;$('#rule-filter').value=eventFilter;$('#rule-search').oninput=debounce(e=>{ruleSearch=e.target.value;rulePage=0;renderRuleTable()},150);$('#rule-asset').onchange=e=>{ruleAsset=e.target.value;ruleOpen=null;rulePage=0;renderRuleTable()};$('#rule-filter').onchange=e=>{eventFilter=e.target.value;rulePage=0;renderRuleTable()};renderRuleTable();
}
function renderRuleTable(){clearGrids();const scoped=ruleAsset==='all'?snapshot:scopeSnapshot(snapshot,ruleAsset),found=ruleAsset==='all'?incidents:incidents.filter(i=>i.assetId===ruleAsset);const filtered=eventRules.filter(r=>`${r.title} ${r.condition}`.toLowerCase().includes(ruleSearch.toLowerCase())&&(eventFilter==='all'||ruleState(r,scoped,found)===eventFilter));rulePage=Math.min(rulePage,Math.max(0,Math.ceil(filtered.length/10)-1));const stateLabels={firing:'발생',pending:'확인 중',missing:'관측 필요',waiting:'조건 감시 중'};
 $('#rule-table').innerHTML=`<div class="rules-table"><div class="rule-table-head"><span>이벤트 규칙</span><span>발생 조건</span><span>지속 시간</span><span>현재 상태</span></div>${filtered.slice(rulePage*10,rulePage*10+10).map(r=>`<section class="rule-item"><button class="rule-row" data-rule="${r.id}" aria-expanded="${ruleOpen===r.id}"><strong>${icon('down',13)}${esc(r.title)}</strong><span>${esc(r.condition)}</span><span>${esc(r.duration)}</span>${pill(ruleState(r,scoped,found),stateLabels[ruleState(r,scoped,found)])}</button>${ruleOpen===r.id?`<div class="rule-detail"><p><b>발생 조건</b> · ${esc(r.condition)} · ${esc(r.duration)}</p><p class="muted-text">${esc(r.requiredIds.map(id=>metricById.get(id)?.title||id).join(' + ')||'Go 서비스 상태')}가 같은 인프라에서 관측되어야 판정합니다. 수집 공백은 지속 조건을 충족하지 않습니다.</p><div class="rule-evidence-list">${(ruleAsset==='all'?assets():assets().filter(a=>a.id===ruleAsset)).map(a=>{const match=found.filter(i=>(i.ruleId||i.id)===r.id&&i.assetId===a.id);return `<div><strong>${esc(a.name)}</strong><span>${esc(match.map(i=>i.evidence.join(' · ')).join(' / ')||stateLabels[ruleState(r,scopeSnapshot(snapshot,a.id),[])])}</span></div>`}).join('')}</div><div class="board-chart-grid" id="rule-charts"></div><button class="filter-button" data-rule-board>관련 인프라를 대시보드에서 보기</button></div>`:''}</section>`).join('')||empty('일치하는 규칙이 없습니다.')}</div><div class="pagination"><span>${filtered.length}개 규칙 · ${rulePage+1} / ${Math.max(1,Math.ceil(filtered.length/10))}</span><button class="filter-button" data-prev ${rulePage===0?'disabled':''}>이전</button><button class="filter-button" data-next ${(rulePage+1)*10>=filtered.length?'disabled':''}>다음</button></div>`;
 $$('[data-rule]').forEach(b=>b.onclick=()=>{ruleOpen=ruleOpen===b.dataset.rule?null:b.dataset.rule;renderRuleTable()});$('[data-prev]').onclick=()=>{rulePage--;ruleOpen=null;renderRuleTable()};$('[data-next]').onclick=()=>{rulePage++;ruleOpen=null;renderRuleTable()};if($('#rule-charts')){const rule=ruleById.get(ruleOpen),roots=ruleAsset==='all'?assets().filter(a=>rule.requiredIds.some(id=>observedForAsset(snapshot,id,a.id))).map(a=>a.id):[ruleAsset],related=relatedAssets(snapshot,roots),ids=related.map(a=>a.id);mountCharts($('#rule-charts'),metricRecipes(ids,eventMetricIds({metricIds:rule.metricIds},related).map(id=>metricById.get(id)).filter(m=>m&&ids.some(id=>observedForAsset(snapshot,m.id,id)))));$('[data-rule-board]').onclick=()=>{selection=ids;focusEvent=groupEvents(incidents).some(g=>g.id===rule.id)?rule.id:null;persist();navigate('dashboard')}}
}
async function loadAudit(root){root.innerHTML=empty('기록을 불러오고 있습니다…');try{const data=await request('audit');if(!root.isConnected)return;const rows=Array.isArray(data)?data:data.events||data.audit||[];root.innerHTML=`<div class="table-wrap"><table><thead><tr><th>시각</th><th>대상</th><th>작업</th><th>결과</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${esc(fullTime(a.time||a.at))}</td><td>${esc(assets().find(x=>x.id===a.assetId)?.name||a.assetId||'서비스')}</td><td>${esc(a.action||a.kind)}</td><td>${esc(a.message||a.detail||a.status)}</td></tr>`).join('')}</tbody></table></div>`}catch(e){root.textContent=e.message}}
function renderSettings(){
 main.innerHTML=pageHeading('','환경설정','')+`<section class="settings-card integration-settings" id="integrations"></section><section class="settings-card" id="mutes"></section><section class="settings-card" id="deliveries"></section><div class="settings-grid"><section class="settings-card"><label>자동 새로고침<select id="refresh-setting">${[0,15,30,60].map(s=>`<option value="${s}" ${s===refreshSeconds?'selected':''}>${s?s+'초':'수동'}</option>`).join('')}</select></label></section><section class="settings-card"><button class="filter-button" id="export-snapshot">관측 데이터 내려받기</button></section></div>`;
 void mountIntegrations($('#integrations'),request,assets());void mountMutes($('#mutes'),assets());void mountDeliveries($('#deliveries'));
 $('#refresh-setting').onchange=e=>{refreshSeconds=Number(e.target.value);savePreference('pulse-display-preferences',{...display,refreshSeconds});schedule()};
 $('#export-snapshot').onclick=()=>download('pulse-observations.json',{...snapshot,incidents});
}
function render(animated=false){if(!snapshot)return;const active=document.activeElement,focusId=active?.id,pos=active?.selectionStart;clearGrids();animateCharts=animated;({dashboard:renderDashboard,infrastructure:renderInfrastructure,events:renderEvents,settings:renderSettings})[page]();animateCharts=false;if(animated)enter(main);if(focusId){const el=document.getElementById(focusId);if(el){el.focus({preventScroll:true});if(typeof pos==='number'&&el.setSelectionRange)el.setSelectionRange(pos,pos)}}}
function navigate(next){if(page===next){render();return}location.hash=next}
function setPage(){page=pages[location.hash.slice(1).split('?')[0]]?location.hash.slice(1).split('?')[0]:'dashboard';const rule=new URLSearchParams(location.hash.split('?')[1]||'').get('rule');if(rule)focusEvent=rule;$('#page-label').textContent=pages[page];$$('[data-page]').forEach(a=>{if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.body.classList.remove('menu-open');$('.sidebar-scrim').hidden=true;$('.mobile-menu').setAttribute('aria-expanded','false');render(true);window.scrollTo({top:0})}
// A redeploy replaces the embedded UI; reload an open page instead of running the old code.
let uiBuild=null,buildCheckedAt=0;
async function checkBuild(){if(Date.now()-buildCheckedAt<30000)return;buildCheckedAt=Date.now();try{const {build}=await (await fetch('/api/health',{cache:'no-store'})).json();const busy=!!document.querySelector('dialog[open]')||chartInteractionActive()||!!document.activeElement?.matches('input,select,textarea');const action=buildAction(uiBuild,build,busy);if(action==='remember')uiBuild=build;else if(action==='reload')location.reload()}catch{}}
worker.onmessage=({data})=>{if(data.type==='ready'){refresh();return}$('#refresh').classList.remove('busy');if(data.type==='error'){notify(data.message+' 이전 관측 이력만 표시합니다.');if(snapshot){snapshot={...snapshot,connected:false,end:Math.floor(Date.now()/1000),metrics:snapshot.metrics.map(m=>({...m,latest:null,state:'stale'})),assets:assets().map(a=>({...a,status:a.enabled?'error':a.status}))};incidents=registeredIncidents(snapshot);render()}$('#service-status').textContent='연결 확인 필요';$('.sidebar-bottom').dataset.state='error';schedule();return}
 const initial=!snapshot;snapshot=data.snapshot;incidents=data.incidents;checkBuild();updateAllCharts(snapshot,refreshSeconds,forceNext);forceNext=false;notify('');$('#updated-at').textContent=clockTime(snapshot.collectedAt);$('#updated-at').title=fullTime(snapshot.collectedAt);$('#service-status').textContent='연결됨';$('.sidebar-bottom').dataset.state='connected';$('#mode-label').textContent=snapshot.mode==='test'?'TEST':'PRODUCTION';$('#nav-event-count').textContent=groupEvents(incidents).length||'';
 // Preserve chart visibility and legend selections during ordinary refreshes.
 const key=JSON.stringify({assets:assets().map(a=>[a.id,a.name,a.status,a.enabled,a.address,a.dependencies,a.tags,a.environment]),observed:snapshot.metrics.map(m=>[m.id,m.series.map(s=>s.labels.assetId)]),events:incidents.map(i=>[i.id,i.status,i.severity])});
 if(chartInteractionActive()){/* charts updated once using their individual cadence */}else if(key!==layoutKey||!main.children.length){layoutKey=key;if((page!=='settings'&&!(page==='events'&&['history','deliveries','audit'].includes(eventTab)))||initial||!main.children.length)render(initial)}else if(page==='dashboard'){/* keep the current charts and selector */}else if(page==='events'&&eventTab==='active'){const group=groupEvents(incidents).find(g=>g.id===focusEvent);if(group){const rows=$$('.board-event-evidence>div');group.incidents.forEach((i,index)=>{if(rows[index]){rows[index].querySelector('span').textContent=`${i.value} ${i.unit}`;rows[index].querySelector('small').textContent=i.evidence.join(' · ')}})}}else if(page==='events'&&eventTab==='rules'){if(ruleOpen){const rule=ruleById.get(ruleOpen),rows=$$('.rule-evidence-list>div'),targets=ruleAsset==='all'?assets():assets().filter(a=>a.id===ruleAsset);targets.forEach((a,index)=>{const row=rows[index];if(!row)return;const found=incidents.filter(i=>i.assetId===a.id&&i.ruleId===ruleOpen);row.querySelector('span').textContent=found.map(i=>i.evidence.join(' · ')).join(' / ')||({missing:'관측 필요',waiting:'조건 감시 중'})[ruleState(rule,scopeSnapshot(snapshot,a.id),[])]||'조건 확인 중'})}else renderRuleTable()}else if(page==='infrastructure'){for(const a of assets()){const row=$$('[data-row]').find(el=>el.dataset.row===a.id);if(row){const stamp=$('[data-last-seen]',row);if(stamp)stamp.title=a.lastSeen?fullTime(a.lastSeen):'관측 전'}}}else if(page!=='settings'&&!(page==='events'&&['history','deliveries','audit'].includes(eventTab)))render();detailUpdate?.();schedule();
};
worker.onerror=()=>{notify('화면 처리기를 시작할 수 없습니다. 새로고침 후 확인하세요.');$('#refresh').classList.remove('busy')};
window.addEventListener('pulse:chart-refresh-changed',schedule);
$('#global-search').onclick=()=>openGlobalSearch(assets(),{asset:showAsset,rule:id=>{eventTab='rules';ruleOpen=id;ruleSearch=ruleById.get(id)?.title||id;ruleAsset='all';eventFilter='all';if(page==='events')render();else navigate('events')},history:()=>{eventTab='history';if(page==='events')render();else navigate('events')},view:applyView});
$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));$('#time-range').onchange=()=>{layoutKey='';refresh()};$('#refresh').onclick=refresh;window.addEventListener('hashchange',setPage);document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(document.hidden)worker.postMessage({type:'stop'});else refresh()});$('.mobile-menu').onclick=()=>{const open=document.body.classList.toggle('menu-open');$('.sidebar-scrim').hidden=!open;$('.mobile-menu').setAttribute('aria-expanded',String(open))};$('.sidebar-scrim').onclick=()=>{document.body.classList.remove('menu-open');$('.sidebar-scrim').hidden=true;$('.mobile-menu').setAttribute('aria-expanded','false')};setPage();refresh();checkBuild();
