import {assetLabels,defaultPorts,isSQLDatabase} from './lib/assets.js';
import {$,$$,esc,icon,dialog,request} from './ui.js';

const sshDefaults={host:'',port:0,username:'',jumpId:'',fingerprint:''};
const input=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
function select(label,name,value,choices){return `<label>${label}<select name="${name}">${Object.entries(choices).map(([id,title])=>`<option value="${esc(id)}" ${String(value)===id?'selected':''}>${esc(title)}</option>`).join('')}</select></label>`}
export function openEditor(asset={},assets=[],onSaved=()=>{}){
 let form={...asset,name:asset.name||'',kind:asset.kind||'server',address:asset.address||'',port:asset.port||0,username:asset.username||'',database:asset.database||'',environment:asset.environment||'',os:asset.os||'linux',tlsMode:asset.tlsMode||'',oracleConnectMode:asset.oracleConnectMode||'service',metricsUrl:asset.metricsUrl||'',dependencies:asset.dependencies||[],ssh:{...sshDefaults,...asset.ssh}};
 let busy=false,deleteArmed=false;
 const d=dialog(asset.id?'인프라 연결 정보':'인프라 등록','빈 값으로 초안을 저장할 수 있습니다. 저장 후 연결 시작을 선택한 대상만 수집합니다.','',{className:'asset-editor'});
 const body=$('.dialog-body',d);
 const read=()=>{
  for(const element of $$('[name]',body)){if(element.name==='key-file'||element.type==='checkbox')continue;if(element.dataset.secret!==undefined&&element.dataset.dirty!=='true')continue;let value=element.value;if(element.type==='number')value=Number(value)||0;if(element.name.startsWith('ssh.'))form.ssh[element.name.slice(4)]=value;else form[element.name]=value}
  form.dependencies=$$('[data-dependency]:checked',body).map(el=>el.value);
 };
 const error=message=>{$('[role=alert]',body).textContent=message};
 const secret=(title,key,exists)=>`<label>${title}<input name="${key}" type="password" autocomplete="new-password" data-secret data-dirty="${form[key]!==undefined}" value="${esc(form[key]??'')}" placeholder="${exists?'저장된 값 유지 · 변경할 때 입력':'선택 입력'}">${exists?`<button type="button" class="plain-link clear-secret" data-clear="${key}">${form[key]===''?'저장 시 기존 값 삭제됨':'저장된 값 삭제'}</button>`:''}</label>`;
 async function operation(work){if(busy)return;busy=true;error('');$$('button',body).forEach(b=>b.disabled=true);try{await work()}catch(e){error(e.message)}finally{busy=false;$$('button',body).forEach(b=>b.disabled=false)}}
 const render=()=>{
  const sql=isSQLDatabase(form.kind),db=sql||form.kind==='redis';
  body.innerHTML=`<form><div class="editor-scroll"><section><h3>${icon('server')} 기본 정보</h3><div class="field-grid">${input('이름','name',form.name,'placeholder="예: 결제 API · 서울"')}${select('유형','kind',form.kind,assetLabels)}${input(form.kind==='application'||form.kind==='http'?'서비스 URL':'주소','address',form.address,'placeholder="호스트 이름 · IP · 서비스 URL"')}${input('포트','port',form.port||'',`type="number" min="1" max="65535" placeholder="${defaultPorts[form.kind]||'기본 포트'}"`)}${input('환경','environment',form.environment,'placeholder="production / staging / test"')}${form.kind==='server'?select('운영체제','os',form.os,{linux:'Linux',windows:'Windows',macos:'macOS'}):''}${form.kind==='application'?input('애플리케이션 계측 URL','metricsUrl',form.metricsUrl,'placeholder="비우면 서비스 URL의 /metrics"'):''}</div></section>
  ${form.kind!=='server'?`<section><h3>${icon('shield')} ${db?'DB 접속':'HTTP 기본 인증'}</h3><div class="field-grid">${input('Username','username',form.username,'autocomplete="off"')}${secret('Password','password',asset.hasPassword)}${form.kind==='oracle'?select('연결 방식','oracleConnectMode',form.oracleConnectMode,{service:'Service name',sid:'SID'}):''}${sql?input(form.kind==='oracle'?(form.oracleConnectMode==='sid'?'SID':'Service name'):'Database','database',form.database):''}${db?select('TLS','tlsMode',form.tlsMode,{'':`기본값 (${sql?'인증서 검증':'사용 안 함'})`,'verify-full':'인증서·호스트 검증',disable:'사용 안 함'}):''}</div>${sql?`<p class="editor-help">읽기 전용 모니터링 계정을 사용하세요. ${form.kind==='postgres'?'등록한 데이터베이스':form.kind==='oracle'?'접속한 서비스의 세션·시스템':'서버 전체 연결·InnoDB'} 통계를 수집합니다. 일부 통계 권한이 없으면 해당 지표를 미관측으로 구분합니다.</p>`:''}</section>`:''}
  <section><h3>${icon('terminal')} SSH · 터미널</h3><div class="field-grid">${input('SSH 주소','ssh.host',form.ssh.host,`placeholder="${form.kind==='server'?'비우면 기본 주소 사용':'터미널을 열 호스트'}"`)}${input('SSH 포트','ssh.port',form.ssh.port||'','type="number" min="1" max="65535" placeholder="22"')}${input('SSH username','ssh.username',form.ssh.username,'autocomplete="off"')}${secret('SSH password','sshPassword',asset.hasSshPassword)}${select('SSH jump · 경유 서버','ssh.jumpId',form.ssh.jumpId,{'':'직접 연결',...Object.fromEntries(assets.filter(a=>a.kind==='server'&&a.id!==asset.id).map(a=>[a.id,a.name]))})}
  <label class="wide">PEM / OpenSSH private key<div class="key-actions"><span>${asset.hasPrivateKey&&form.privateKey===undefined?'키 저장됨 · 기존 키 유지':'키 파일 또는 텍스트 입력'}</span><input type="file" name="key-file" aria-label="키 파일 선택"></div><textarea name="privateKey" aria-label="Private key" data-secret data-dirty="${form.privateKey!==undefined}" class="private-key-input" autocomplete="off" spellcheck="false" rows="3" placeholder="-----BEGIN OPENSSH PRIVATE KEY-----">${esc(form.privateKey??'')}</textarea>${asset.hasPrivateKey?'<button type="button" class="plain-link clear-secret" data-clear="privateKey">저장된 키 삭제</button>':''}</label>${secret('Key passphrase','passphrase',asset.hasPassphrase)}${input('서버 지문 · SHA256','ssh.fingerprint',form.ssh.fingerprint,'placeholder="SHA256:…"')}</div>
  <p class="editor-help">경유 서버를 먼저 등록하세요. DB·HTTP도 선택한 SSH 경유 경로를 사용합니다. 서버 지문은 별도로 확인해 저장하며 개인 키를 자동으로 읽지 않습니다.</p>${asset.id?`<div class="fingerprint-inspect"><button type="button" class="filter-button" data-fingerprint>저장된 주소의 지문 조회</button><div data-pin></div></div>`:''}</section>
  <section><h3>연결 관계</h3><p class="editor-help">이 인프라가 사용하는 DB·캐시·서버를 선택하면 관련 이벤트 그래프에 함께 표시합니다.</p><div class="dependency-options">${assets.filter(a=>a.id!==asset.id).map(a=>`<label><input type="checkbox" data-dependency value="${esc(a.id)}" ${form.dependencies.includes(a.id)?'checked':''}><span>${esc(a.name)}<small>${assetLabels[a.kind]}</small></span></label>`).join('')||'다른 인프라를 등록한 후 선택할 수 있습니다.'}</div></section></div>
  <div class="editor-footer"><p class="form-error" role="alert"></p><span>${icon('shield',14)} 비밀값은 암호화해 저장</span>${asset.id?'<button type="button" class="plain-link clear-secret" data-delete>등록 삭제</button>':''}<button type="button" class="filter-button" data-cancel>취소</button><button type="submit" class="primary-button">${asset.id?'변경 저장':'초안 등록'}</button></div></form>`;
  $('form',body).onsubmit=e=>{e.preventDefault();read();void operation(async()=>{const saved=await request(asset.id?`assets/${asset.id}`:'assets',asset.id?'PUT':'POST',form);d.close();onSaved(saved)})};
  $('[data-cancel]',body).onclick=()=>d.close();
  $$('[data-secret]',body).forEach(el=>el.oninput=()=>el.dataset.dirty='true');
  $$('[data-clear]',body).forEach(button=>button.onclick=()=>{const field=$(`[name="${button.dataset.clear}"]`,body);field.value='';field.dataset.dirty='true';button.textContent='저장 시 기존 값 삭제됨'});
  $('[name=kind]',body).onchange=()=>{read();form.port=0;form.database='';form.oracleConnectMode='service';render()};
  $('[name=oracleConnectMode]',body)?.addEventListener('change',()=>{read();render()});
  $('[name=key-file]',body).onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>131072){error('키 파일은 128KB 이하로 선택하세요.');return}const field=$('[name=privateKey]',body);field.value=await file.text();field.dataset.dirty='true'};
  $('[data-fingerprint]',body)?.addEventListener('click',()=>operation(async()=>{const result=await request(`assets/${asset.id}/fingerprint`,'POST');const pin=$('[data-pin]',body);pin.innerHTML=`<code>${esc(result.fingerprint)}</code><p>서버 관리자가 제공한 지문과 일치하는지 확인한 후 적용하세요.</p><button type="button" class="filter-button">확인한 지문 적용</button>`;$('button',pin).onclick=()=>{$('[name="ssh.fingerprint"]',body).value=result.fingerprint;pin.replaceChildren()}}));
  $('[data-delete]',body)?.addEventListener('click',()=>{if(!deleteArmed){deleteArmed=true;$('[data-delete]',body).textContent='등록 삭제 확인';return}void operation(async()=>{await request(`assets/${asset.id}`,'DELETE');d.close();onSaved()})});
 };
 render();d.addEventListener('cancel',e=>{if(busy)e.preventDefault()});
}
export async function openCandidates(assets,onSaved){
 const d=dialog('SSH 연결 후보','Windows · Linux · macOS 설정의 호스트 후보를 등록 양식으로 가져옵니다.','<p>후보 확인 중…</p>');
 try{const response=await fetch('/api/connections');if(!response.ok)throw new Error('후보 목록을 읽을 수 없습니다.');const data=await response.json();if(!d.isConnected)return;
  $('.dialog-body',d).innerHTML=`<p class="editor-help">${esc(data.notice)}</p><div class="targets-list">${data.hosts.map((h,i)=>`<article class="ssh-host"><h3>${esc(h.alias)} <small>${esc(h.platform)}</small></h3><p>${esc(h.user||'username 미입력')}@${esc(h.hostname)}:${esc(h.port||22)}</p>${h.proxyJump?`<p>경유 설정: ${esc(h.proxyJump)} · 등록 화면에서 별도로 선택</p>`:''}<button class="filter-button" data-candidate="${i}">등록 정보로 가져오기 ${icon('arrow',14)}</button></article>`).join('')||'<p>발견된 호스트가 없습니다.</p>'}</div>`;
  $$('[data-candidate]',d).forEach(b=>b.onclick=()=>{const h=data.hosts[Number(b.dataset.candidate)];d.close();openEditor({name:h.alias,kind:'server',address:h.hostname,port:Number(h.port)||22,ssh:{...sshDefaults,username:h.user||''}},assets,onSaved)});
 }catch(e){$('.dialog-body',d).textContent=e.message}
}
