import {$,$$,esc,dialog,request,fullTime,download} from './ui.js';
import {assetLabels} from './lib/assets.js';
import {eventRules} from './lib/rule-catalog.js';

export const splitLabels=value=>[...new Set(String(value||'').split(',').map(v=>v.trim()).filter(Boolean))];
export const assetSearchText=a=>[a.name,a.address,a.environment,a.kind,...(a.tags||[])].join(' ').toLowerCase();
const options=(items,selected=[])=>items.map(([id,name])=>`<option value="${esc(id)}" ${selected.includes(id)?'selected':''}>${esc(name)}</option>`).join('');
export const assetOptions=(assets,selected=[])=>options(assets.map(a=>[a.id,a.name]),selected);
const status={queued:'전송 대기',sent:'전송 성공',retrying:'재시도 대기',failed:'전송 실패',suppressed:'점검 중 억제',cancelled:'취소',requeued:'재전송 예약'};
const workflow={open:'미처리',acknowledged:'확인함',in_progress:'처리 중',resolved:'처리 완료'};
const actual={firing:'장애 지속',resolved:'복구 확인',cancelled:'수집·설정 변경',test:'테스트',summary:'운영 요약'};
const notice=(root,message)=>{const el=$('[data-notice]',root);if(el)el.textContent=message};
const busy=async(button,work,onError)=>{button.disabled=true;try{await work()}catch(e){onError(e.message)}finally{button.disabled=false}};

export async function mountDeliveries(root,api=request){
 root.innerHTML='<div class="integration-heading"><div><h2>알림 전송 이력</h2><p>최근 90일 이력에서 최대 500건을 조회합니다. 실패한 알림은 현재 수신처로 다시 보낼 수 있습니다.</p></div><button class="filter-button" data-reload>새로고침</button></div><div class="toolbar"><input data-query aria-label="전송 이력 검색" placeholder="이벤트 · 대상 · 연동 검색"><select data-status aria-label="전송 결과"><option value="">모든 결과</option>'+Object.entries(status).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')+'</select></div><p role="status" data-notice></p><div data-rows></div>';
 let page=0,items=[];const render=()=>{const q=$('[data-query]',root).value.toLowerCase(),filter=$('[data-status]',root).value,found=items.filter(v=>(!filter||v.status===filter)&&[v.event.title,v.event.assetName,v.integrationName].join(' ').toLowerCase().includes(q));page=Math.min(page,Math.max(0,Math.ceil(found.length/25)-1));$('[data-rows]',root).innerHTML=found.slice(page*25,page*25+25).map(v=>`<article class="ops-row"><div><strong>${esc(v.event.title)}</strong><p>${esc(v.event.assetName)} · ${esc(v.integrationName)}</p><small>${esc(fullTime(v.at))} · ${esc(status[v.status]||v.status)} · 시도 ${v.attempts}회</small>${v.error?`<p class="form-error">${esc(v.error)}</p>`:''}</div><div class="row-actions"><button class="filter-button" data-detail="${esc(v.id)}">내용</button>${v.status==='failed'?`<button class="filter-button" data-retry="${esc(v.id)}">재전송</button>`:''}</div></article>`).join('')||'<p class="muted-text">일치하는 전송 기록이 없습니다.</p>';
  const rows=$('[data-rows]',root);rows.insertAdjacentHTML('beforeend',`<div class="pagination"><span>${found.length}건 · ${page+1} / ${Math.max(1,Math.ceil(found.length/25))}</span><button class="filter-button" data-prev ${page===0?'disabled':''}>이전</button><button class="filter-button" data-next ${(page+1)*25>=found.length?'disabled':''}>다음</button></div>`);$('[data-prev]',root).onclick=()=>{page--;render()};$('[data-next]',root).onclick=()=>{page++;render()};
  $$('[data-detail]',root).forEach(b=>b.onclick=()=>{const v=items.find(v=>v.id===b.dataset.detail);dialog(v.event.title,'전송 당시의 대상·조건·관측값입니다.',`<p>${esc(status[v.status])} · ${esc(v.integrationName)}</p><pre class="ops-preview">${esc(JSON.stringify(v.event,null,2))}</pre>`)});
  $$('[data-retry]',root).forEach(b=>b.onclick=()=>busy(b,async()=>{const v=items.find(v=>v.id===b.dataset.retry);const result=await api(`deliveries/${v.id}/retry`,'POST',{version:v.version});await load();notice(root,result.message)},message=>notice(root,message)));
 };
 const load=async()=>{try{items=await api('deliveries');if(root.isConnected)render()}catch(e){notice(root,e.message)}};
 $('[data-reload]',root).onclick=load;$('[data-query]',root).oninput=()=>{page=0;render()};$('[data-status]',root).onchange=()=>{page=0;render()};await load();
}

export async function mountEventHistory(root,api=request){
 root.innerHTML='<div class="integration-heading"><div><h2>이벤트 처리 이력</h2><p>처리 상태와 실제 복구 상태를 함께 기록합니다. 처리 완료를 선택해도 장애 판정과 알림은 계속됩니다.</p></div><button class="filter-button" data-reload>새로고침</button></div><div class="toolbar"><input data-query aria-label="이벤트 이력 검색" placeholder="대상 · 이벤트 · 태그 · 메모 검색"><select data-workflow aria-label="처리 상태"><option value="">모든 처리 상태</option>'+Object.entries(workflow).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')+'</select><select data-actual aria-label="실제 복구 상태"><option value="">모든 실제 상태</option><option value="firing">장애 지속</option><option value="resolved">복구 확인</option><option value="cancelled">수집·설정 변경</option></select></div><p role="status" data-notice></p><div data-rows></div>';
 let items=[],page=0;
 const render=()=>{const q=$('[data-query]',root).value.toLowerCase(),w=$('[data-workflow]',root).value,a=$('[data-actual]',root).value,found=items.filter(v=>(!w||v.workflow===w)&&(!a||v.event.status===a)&&[v.event.title,v.event.assetName,v.event.environment,...(v.event.tags||[]),...v.notes.map(n=>n.text)].join(' ').toLowerCase().includes(q));page=Math.min(page,Math.max(0,Math.ceil(found.length/25)-1));$('[data-rows]',root).innerHTML=found.slice(page*25,page*25+25).map(v=>`<article class="ops-row"><div><strong>${esc(v.event.title)}</strong><p>${esc(v.event.assetName)} · ${esc(v.event.environment)}</p><small>${esc(actual[v.event.status])} · ${esc(workflow[v.workflow])} · ${esc(fullTime(v.event.at))}${v.resolvedAt?' → '+esc(fullTime(v.resolvedAt)):''}</small>${v.notes.length?`<p class="note-excerpt">${esc(v.notes.at(-1).text)}</p>`:''}</div><button class="filter-button" data-event-record="${esc(v.id)}">처리·메모 ${v.notes.length?'('+v.notes.length+')':''}</button></article>`).join('')||'<p class="muted-text">이벤트 이력이 없습니다.</p>';
  $('[data-rows]',root).insertAdjacentHTML('beforeend',`<div class="pagination"><span>${found.length}건 · ${page+1} / ${Math.max(1,Math.ceil(found.length/25))}</span><button class="filter-button" data-prev ${page===0?'disabled':''}>이전</button><button class="filter-button" data-next ${(page+1)*25>=found.length?'disabled':''}>다음</button></div>`);$('[data-prev]',root).onclick=()=>{page--;render()};$('[data-next]',root).onclick=()=>{page++;render()};
  $$('[data-event-record]',root).forEach(b=>b.onclick=()=>{const v=items.find(v=>v.id===b.dataset.eventRecord),d=dialog(v.event.title,`${v.event.assetName} · ${actual[v.event.status]}`,`<p>${esc(v.event.condition||'연결 상태 확인')}</p><form class="ops-form"><label>처리 상태<select name="workflow">${options(Object.entries(workflow),[v.workflow])}</select></label><label>새 메모<textarea name="note" maxlength="2000" rows="4" placeholder="확인 내용과 조치 내용을 남기세요"></textarea></label><div class="event-notes">${v.notes.map(n=>`<article><small>${esc(fullTime(n.at))}</small><p>${esc(n.text)}</p></article>`).join('')}</div><p role="alert" data-notice></p><div class="dialog-actions"><button class="primary-button">저장</button></div></form>`);$('form',d).onsubmit=e=>{e.preventDefault();const f=e.target;void busy($('button',f),async()=>{await api(`events/${v.id}`,'PUT',{version:v.version,workflow:f.elements.workflow.value,note:f.elements.note.value});d.close();await load()},message=>notice(d,message))}});
 };
 const load=async()=>{try{items=await api('events');if(root.isConnected)render()}catch(e){notice(root,e.message)}};$('[data-reload]',root).onclick=load;for(const sel of ['[data-query]','[data-workflow]','[data-actual]'])$(sel,root).addEventListener(sel==='[data-query]'?'input':'change',()=>{page=0;render()});await load();
}
const localDate=value=>{const d=new Date(value*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
export function openMute(item,assets,onSaved,api=request){
 const now=Math.floor(Date.now()/1000),d=dialog(item.id?'점검 시간 수정':'음소거·점검 시간 추가','알림을 멈춰도 수집과 이벤트 이력은 계속됩니다. 종료 시각에 자동으로 해제합니다.',`<form class="ops-form"><label>이름<input name="name" value="${esc(item.name||'')}" maxlength="120" required placeholder="예: DB 정기 점검"></label><div class="field-grid"><label>시작 · 브라우저 시간<input name="start" type="datetime-local" value="${localDate(item.startsAt||now)}" required></label><label>종료 · 브라우저 시간<input name="end" type="datetime-local" value="${localDate(item.endsAt||now+3600)}" required></label></div><div class="row-actions"><button type="button" class="filter-button" data-minutes="15">지금부터 15분</button><button type="button" class="filter-button" data-minutes="60">지금부터 1시간</button></div><label>대상 인프라 · 선택하지 않으면 전체<select name="assets" multiple size="5">${assetOptions(assets,item.assetIds)}</select></label><div class="field-grid"><label>환경 · 쉼표로 구분<input name="envs" value="${esc((item.environments||[]).join(', '))}" placeholder="비우면 모든 환경"></label><label>필수 태그 · 쉼표로 구분<input name="tags" value="${esc((item.tags||[]).join(', '))}" placeholder="비우면 모든 태그"></label></div><p class="modal-footnote">인프라·환경·태그 조건을 모두 충족하는 대상에 적용합니다. 최대 31일까지 설정할 수 있습니다.</p><p role="alert" data-notice></p><div class="dialog-actions"><button class="primary-button">저장</button></div></form>`),form=$('form',d);
 $$('[data-minutes]',d).forEach(b=>b.onclick=()=>{const now=Math.floor(Date.now()/1000);form.elements.start.value=localDate(now);form.elements.end.value=localDate(now+Number(b.dataset.minutes)*60)});
 form.onsubmit=e=>{e.preventDefault();void busy($('button.primary-button',form),async()=>{await api(item.id?`mutes/${item.id}`:'mutes',item.id?'PUT':'POST',{version:item.version||0,name:form.elements.name.value.trim(),assetIds:[...form.elements.assets.selectedOptions].map(o=>o.value),environments:splitLabels(form.elements.envs.value),tags:splitLabels(form.elements.tags.value),startsAt:Math.floor(new Date(form.elements.start.value).getTime()/1000),endsAt:Math.floor(new Date(form.elements.end.value).getTime()/1000)});d.close();await onSaved()},message=>notice(d,message))};return d;
}
export async function mountMutes(root,assets,api=request){
 root.innerHTML='<div class="integration-heading"><div><h2>음소거·점검 시간</h2><p>예정된 점검과 임시 음소거를 한 곳에서 관리합니다.</p></div><button class="primary-button" data-add-mute>점검 시간 추가</button></div><p role="status" data-notice></p><div data-rows></div>';
 const load=async()=>{try{const items=await api('mutes');if(!root.isConnected)return;const now=Date.now()/1000;$('[data-rows]',root).innerHTML=items.map(m=>`<article class="ops-row"><div><strong>${esc(m.name)}</strong> <span class="health-label ${now>=m.endsAt?'paused':now<m.startsAt?'draft':'warning'}">${now>=m.endsAt?'종료':now<m.startsAt?'예정':'알림 음소거 중'}</span><p>${esc(fullTime(m.startsAt))} – ${esc(fullTime(m.endsAt))}</p><small>${esc(m.assetIds.length?m.assetIds.map(id=>assets.find(a=>a.id===id)?.name||'삭제된 대상').join(', '):'전체 인프라')}${m.environments.length?' · '+esc(m.environments.join(', ')):''}${m.tags.length?' · '+esc(m.tags.join(', ')):''}</small></div><div class="row-actions"><button class="filter-button" data-edit-mute="${m.id}">수정</button><button class="filter-button" data-delete-mute="${m.id}">${now>=m.endsAt?'삭제':'즉시 해제'}</button></div></article>`).join('')||'<p class="muted-text">등록된 점검 시간이 없습니다.</p>';$$('[data-edit-mute]',root).forEach(b=>b.onclick=()=>openMute(items.find(m=>m.id===b.dataset.editMute),assets,load,api));$$('[data-delete-mute]',root).forEach(b=>b.onclick=()=>busy(b,async()=>{await api(`mutes/${b.dataset.deleteMute}`,'DELETE');await load()},message=>notice(root,message)))}catch(e){notice(root,e.message)}};
 $('[data-add-mute]',root).onclick=()=>openMute({},assets,load,api);await load();
}

export function parseAssetCSV(text){
 // RFC 4180 quoted fields, CRLF, embedded commas/newlines, and a UTF-8 BOM.
 const rows=[];let row=[],field='',quoted=false,closed=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"'){quoted=false;closed=true}else field+=c;continue}
  if(c==='"'){if(field||closed)throw new Error('CSV 따옴표 위치를 확인하세요');quoted=true}
  else if(c===','){row.push(field);field='';closed=false}
  else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';closed=false}
  else{if(closed)throw new Error('따옴표 뒤에는 구분자만 사용할 수 있습니다');field+=c}
 }if(quoted)throw new Error('CSV 따옴표가 닫히지 않았습니다');row.push(field);if(row.some(v=>v.trim()))rows.push(row);
 if(rows.length<2)throw new Error('헤더와 한 개 이상의 인프라 행이 필요합니다');
 const headers=rows.shift().map(v=>v.replace(/^\uFEFF/,'').trim()),allowed=['name','kind','address','port','username','database','environment','tags','metricsUrl','os','tlsMode','sshHost','sshPort','sshUsername','sshJumpId','sshFingerprint'];
 if(!headers.includes('name')||!headers.includes('kind')||headers.some(v=>!allowed.includes(v))||new Set(headers).size!==headers.length)throw new Error('CSV 헤더를 확인하세요. name과 kind는 필수입니다');
 if(rows.length>100)throw new Error('CSV는 한 번에 최대 100개까지 등록합니다');
 return rows.map((values,index)=>{if(values.length!==headers.length)throw new Error(`${index+2}행 열 수를 확인하세요`);const raw=Object.fromEntries(headers.map((key,i)=>[key,values[i].trim()]));if(!Object.hasOwn(assetLabels,raw.kind))throw new Error(`${index+2}행 유형을 확인하세요`);for(const key of ['port','sshPort'])if(raw[key]&&!/^[0-9]+$/.test(raw[key]))throw new Error(`${index+2}행 포트를 확인하세요`);const asset={name:raw.name,kind:raw.kind,address:raw.address||'',port:Number(raw.port)||0,environment:raw.environment||'',tags:splitLabels(raw.tags),ssh:{host:raw.sshHost||'',port:Number(raw.sshPort)||0,username:raw.sshUsername||'',jumpId:raw.sshJumpId||'',fingerprint:raw.sshFingerprint||''},dependencies:[]};for(const key of ['username','database','metricsUrl','os','tlsMode'])if(raw[key])asset[key]=raw[key];return asset});
}
export function openCSVImport(onSaved,api=request){
 const d=dialog('CSV 인프라 일괄 등록','최대 100개를 초안으로 등록합니다. 인증 정보는 각 연결 정보에서 입력하세요.',`<div class="ops-form"><button class="filter-button" data-template>CSV 양식 내려받기</button><label>CSV 파일<input type="file" accept=".csv,text/csv" data-file></label><label>또는 CSV 붙여넣기<textarea rows="8" data-csv placeholder="name,kind,address,port,environment,tags"></textarea></label><button class="filter-button" data-preview>등록 전 확인</button><div data-preview-list></div><p role="status" data-notice></p><button class="primary-button" data-import disabled>초안 등록</button></div>`);let parsed=[];
 $('[data-template]',d).onclick=()=>download('pulse-assets.csv','name,kind,address,port,environment,tags,sshUsername\r\nExample API,http,https://example.invalid,443,staging,"service-api,team-platform",\r\n','text/csv;charset=utf-8');
 $('[data-file]',d).onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>200000){notice(d,'CSV 파일은 200KB 이하로 선택하세요');return}$('[data-csv]',d).value=await file.text();parsed=[];$('[data-import]',d).disabled=true};
 $('[data-csv]',d).oninput=()=>{parsed=[];$('[data-import]',d).disabled=true};
 $('[data-preview]',d).onclick=()=>{try{parsed=parseAssetCSV($('[data-csv]',d).value);$('[data-preview-list]',d).innerHTML=`<p>${parsed.length}개 초안</p><div class="ops-preview">${parsed.map(a=>`<p>${esc(a.name)} · ${esc(assetLabels[a.kind])} · ${esc(a.address)}</p>`).join('')}</div>`;$('[data-import]',d).disabled=false;notice(d,'')}catch(e){parsed=[];$('[data-import]',d).disabled=true;notice(d,e.message)}};
 $('[data-import]',d).onclick=e=>busy(e.target,async()=>{const results=await api('assets/import','POST',{assets:parsed});parsed=[];const errors=results.filter(r=>r.error);if(errors.length){notice(d,errors.map(r=>`${r.row}행: ${r.error}`).join(' · '));$('[data-import]',d).remove();await onSaved()}else{d.close();await onSaved()}},message=>notice(d,message));return d;
}
export function bindBulkInfrastructure(root,assets,onSaved,api=request){
 const selected=()=>$$('[data-select-asset]:checked',root).map(el=>assets.find(a=>a.id===el.value)).filter(Boolean),update=()=>{$$('[data-bulk]',root).forEach(b=>b.disabled=!selected().length);$('[data-selection-count]',root).textContent=`${selected().length}개 선택`};
 $('[data-select-all]',root).onchange=e=>{$$('[data-select-asset]',root).filter(el=>!el.closest('tr').hidden).forEach(el=>el.checked=e.target.checked);update()};
 $$('[data-select-asset]',root).forEach(el=>el.onchange=update);update();
 $$('[data-bulk]',root).forEach(b=>b.onclick=()=>{const chosen=selected();if(b.dataset.bulk==='update'){const d=dialog('공통 설정 변경','저장한 대상은 수집을 멈춥니다. 변경 후 일괄 연결 시작을 선택하세요.','<form class="ops-form"><label class="check-field"><input name="changeEnv" type="checkbox">환경 변경</label><input name="environment" aria-label="공통 환경" placeholder="production"><label class="check-field"><input name="changeTags" type="checkbox">태그 전체 교체</label><input name="tags" aria-label="공통 태그" placeholder="service-api, team-platform"><p role="alert" data-notice></p><button class="primary-button">선택 대상에 적용</button></form>');$('form',d).onsubmit=e=>{e.preventDefault();const f=e.target,data={action:'update',items:chosen.map(a=>({id:a.id,version:a.version}))};if(f.elements.changeEnv.checked)data.environment=f.elements.environment.value.trim();if(f.elements.changeTags.checked)data.tags=splitLabels(f.elements.tags.value);if(!Object.hasOwn(data,'environment')&&!Object.hasOwn(data,'tags')){notice(d,'변경할 항목을 선택하세요');return}void busy($('button',f),async()=>{const results=await api('assets/bulk','POST',data);d.close();showBulkResult(results);onSaved()},message=>notice(d,message))};return}
  void busy(b,async()=>{const results=await api('assets/bulk','POST',{action:b.dataset.bulk,items:chosen.map(a=>({id:a.id,version:a.version}))});showBulkResult(results);onSaved()},message=>dialog('일괄 작업 결과','',`<p>${esc(message)}</p>`));
 });
}
function showBulkResult(results){const failed=results.filter(r=>r.error);dialog('일괄 작업 결과',`성공 ${results.length-failed.length}개 · 실패 ${failed.length}개`,`<p>연결 시작은 수집 상태에서 결과를 확인하세요.</p>${failed.map(r=>`<p>${esc(r.id)}: ${esc(r.error)}</p>`).join('')}`)}
export async function openDiagnostic(asset,api=request){
 const d=dialog(asset.name+' 연결 진단','저장된 설정으로 DNS·포트·프로토콜·지표 권한을 확인합니다.','<p role="status" data-notice>진단 중…</p><div data-steps></div>');
 try{const steps=await api(`assets/${asset.id}/diagnose`,'POST');if(!d.isConnected)return;notice(d,'진단 완료');$('[data-steps]',d).innerHTML=steps.map(v=>`<article class="ops-row"><div><strong>${esc(v.name)}</strong><p>${esc(v.detail)}</p></div><span class="health-label ${v.status==='ok'?'connected':v.status==='skipped'?'paused':'warning'}">${esc({ok:'성공',failed:'실패',warning:'확인 필요',skipped:'경유 확인'}[v.status])}</span></article>`).join('')}catch(e){if(d.isConnected)notice(d,e.message)}return d;
}
let activeViewId='';
export async function mountViews(root,read,apply,api=request){
 root.innerHTML='<div class="row-actions"><label class="sr-only" for="saved-view">저장된 대시보드</label><select id="saved-view"><option value="">저장된 대시보드 선택</option></select><button class="filter-button" data-save-view>현재 보기 저장</button><button class="filter-button" data-manage-view disabled>선택 보기 관리</button></div><p role="status" data-notice></p>';let items=[];
 const load=async()=>{try{items=await api('views');if(!root.isConnected)return;$('#saved-view',root).innerHTML='<option value="">저장된 대시보드 선택</option>'+options(items.map(v=>[v.id,v.name]),[activeViewId]);$('[data-manage-view]',root).disabled=!items.some(v=>v.id===activeViewId)}catch(e){notice(root,e.message)}};
 $('#saved-view',root).onchange=e=>{activeViewId=e.target.value;const item=items.find(v=>v.id===e.target.value);$('[data-manage-view]',root).disabled=!item;if(item)apply(item)};
 const save=item=>{const d=dialog(item?'저장된 대시보드 관리':'대시보드 이름 저장','인프라 선택·조회 기간·자동 새로고침을 저장합니다.',`<form class="ops-form"><label>이름<input name="name" value="${esc(item?.name||'')}" maxlength="120" required placeholder="예: 서비스 A 운영"></label><p>${read().assetIds.length}개 인프라 선택</p><p role="alert" data-notice></p><div class="dialog-actions">${item?'<button type="button" class="plain-link" data-delete-view>저장된 보기 삭제</button>':''}<button class="primary-button">현재 설정 저장</button></div></form>`);$('form',d).onsubmit=e=>{e.preventDefault();void busy($('button.primary-button',d),async()=>{const saved=await api(item?`views/${item.id}`:'views',item?'PUT':'POST',{...read(),name:e.target.elements.name.value.trim(),version:item?.version||0});activeViewId=saved.id;d.close();await load()},message=>notice(d,message))};let armed=false;$('[data-delete-view]',d)?.addEventListener('click',e=>{if(!armed){armed=true;e.target.textContent='삭제 확인';return}void busy(e.target,async()=>{await api(`views/${item.id}`,'DELETE');activeViewId='';d.close();await load()},message=>notice(d,message))});return d};
 $('[data-save-view]',root).onclick=()=>save();$('[data-manage-view]',root).onclick=()=>save(items.find(v=>v.id===$('#saved-view',root).value));await load();
}
export async function openGlobalSearch(assets,handlers,api=request){
 const d=dialog('전체 검색','이름·주소·환경·태그·이벤트·규칙·저장된 대시보드를 검색합니다.','<input class="global-search-input" aria-label="전체 검색" placeholder="서비스 · 팀 · 태그 · 이벤트 검색" autofocus><p role="status" data-notice></p><div data-results></div>');let events=[],views=[];
 const render=()=>{const q=$('input',d).value.trim().toLowerCase();if(!q){$('[data-results]',d).textContent='검색어를 입력하세요';return}
  const found=[...assets.filter(a=>assetSearchText(a).includes(q)).map(a=>({name:a.name,detail:'인프라 · '+(a.tags||[]).join(', '),open:()=>handlers.asset(a)})),...eventRules.filter(v=>(v.title+' '+v.condition).toLowerCase().includes(q)).map(v=>({name:v.title,detail:'이벤트 규칙 · '+v.condition,open:()=>handlers.rule(v.id)})),...events.filter(v=>[v.event.title,v.event.assetName,...v.notes.map(n=>n.text)].join(' ').toLowerCase().includes(q)).map(v=>({name:v.event.title,detail:'이벤트 이력 · '+v.event.assetName,open:()=>handlers.history()})),...views.filter(v=>v.name.toLowerCase().includes(q)).map(v=>({name:v.name,detail:'저장된 대시보드',open:()=>handlers.view(v)}))].slice(0,50);
  $('[data-results]',d).innerHTML=found.map((v,index)=>`<button class="search-result" data-result="${index}"><strong>${esc(v.name)}</strong><small>${esc(v.detail)}</small></button>`).join('')||'<p>검색 결과가 없습니다.</p>';$$('[data-result]',d).forEach(b=>b.onclick=()=>{d.close();found[Number(b.dataset.result)].open()});
 };$('input',d).oninput=render;render();const results=await Promise.allSettled([api('events'),api('views')]);if(!d.isConnected)return d;if(results[0].status==='fulfilled')events=results[0].value;if(results[1].status==='fulfilled')views=results[1].value;if(results.some(v=>v.status==='rejected'))notice(d,'일부 이력을 읽지 못했습니다. 인프라와 규칙 검색을 사용할 수 있습니다.');render();return d;
}
