"use client";
import {useEffect,useRef,useState} from 'react';
import {KeyRound,Upload,ShieldCheck,Server,Terminal,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {assetLabels,controlRequest,type Asset,type AssetInput,type AssetKind} from '@/lib/monitoring/assets';
export function AssetEditor({asset,assets,onClose,onSaved}:{asset:Partial<Asset>|null;assets:Asset[];onClose:()=>void;onSaved:(asset:Asset)=>void}){
 const [form,setForm]=useState<AssetInput>(()=>({...asset,name:asset?.name||'',kind:asset?.kind||'server',address:asset?.address||'',port:asset?.port||0,username:asset?.username||'',database:asset?.database||'',environment:asset?.environment||'',os:asset?.os||'linux',tlsMode:asset?.tlsMode||'',metricsUrl:asset?.metricsUrl||'',dependencies:asset?.dependencies||[],ssh:asset?.ssh||{host:'',port:0,username:'',jumpId:'',fingerprint:''}}));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[pin,setPin]=useState(''),[deleteArmed,setDeleteArmed]=useState(false);const file=useRef<HTMLInputElement>(null);
 const set=(key:keyof AssetInput,value:unknown)=>setForm(f=>({...f,[key]:value}));
 const ssh=(key:keyof Asset['ssh'],value:string|number)=>setForm(f=>({...f,ssh:{...f.ssh!,[key]:value}}));
 const secret=(key:'password'|'sshPassword'|'privateKey'|'passphrase',title:string,exists:boolean|undefined)=><label>{title}<input type="password" autoComplete="new-password" value={form[key]??''} onChange={e=>set(key,e.target.value)} placeholder={exists?'저장된 값 유지 · 변경할 때 입력':'선택 입력'}/>{exists&&<button type="button" className="plain-link clear-secret" onClick={()=>set(key,'')}>{form[key]===''?'저장 시 기존 값 삭제됨':'저장된 값 삭제'}</button>}</label>;
 const save=async()=>{setBusy(true);setError('');try{const saved=await controlRequest<Asset>(asset?.id?`assets/${asset.id}`:'assets',asset?.id?'PUT':'POST',form);onSaved(saved)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const inspect=async()=>{setBusy(true);setError('');try{const result=await controlRequest<{fingerprint:string}>(`assets/${asset?.id}/fingerprint`,'POST');setPin(result.fingerprint)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const remove=async()=>{if(!deleteArmed){setDeleteArmed(true);return}setBusy(true);setError('');try{await controlRequest(`assets/${asset!.id}`,'DELETE');onSaved(asset as Asset)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const database=form.kind==='postgres'||form.kind==='redis';
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="asset-editor"><DialogHeader><div className="eyebrow">YOUR INFRASTRUCTURE</div><DialogTitle>{asset?.id?'인프라 연결 정보':'인프라 등록'}</DialogTitle><DialogDescription>빈 값으로 먼저 등록할 수 있습니다. 저장 후 ‘연결 시작’을 누르면 수집합니다.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void save()}}>
 <div className="editor-scroll"><section><h3><Server size={16}/> 기본 정보</h3><div className="field-grid"><label>이름<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="예: 결제 API · 서울"/></label><label>유형<select value={form.kind} onChange={e=>set('kind',e.target.value as AssetKind)}>{Object.entries(assetLabels).map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label><label className="wide">{form.kind==='http'||form.kind==='application'?'서비스 URL':'주소'}<input value={form.address} onChange={e=>set('address',e.target.value)} placeholder={form.kind==='http'||form.kind==='application'?'https://service.example.com':'호스트 이름 또는 IP'}/></label>{!(form.kind==='http'||form.kind==='application')&&<label>포트<input type="number" min={1} max={65535} value={form.port||''} onChange={e=>set('port',Number(e.target.value))} placeholder={form.kind==='postgres'?'5432':form.kind==='redis'?'6379':'22'}/></label>}<label>환경<input value={form.environment} onChange={e=>set('environment',e.target.value)} placeholder="production / staging / test"/></label>{form.kind==='server'&&<label>운영체제<select value={form.os} onChange={e=>set('os',e.target.value)}><option value="linux">Linux</option><option value="windows">Windows</option><option value="macos">macOS</option></select></label>}{form.kind==='application'&&<label className="wide">애플리케이션 계측 URL<input value={form.metricsUrl} onChange={e=>set('metricsUrl',e.target.value)} placeholder="비우면 서비스 URL의 /metrics"/><small>등록한 앱의 계측을 직접 읽어 응답 분포와 변화율을 계산합니다.</small></label>}</div></section>
 {form.kind!=='server'&&<section><h3><KeyRound size={16}/> {database?'DB 접속':'HTTP 기본 인증'}</h3><div className="field-grid"><label>Username<input autoComplete="off" value={form.username} onChange={e=>set('username',e.target.value)} placeholder="선택 입력"/></label>{secret('password','Password',asset?.hasPassword)}{form.kind==='postgres'&&<label>Database<input value={form.database} onChange={e=>set('database',e.target.value)} placeholder="postgres"/></label>}{database&&<label>TLS<select value={form.tlsMode} onChange={e=>set('tlsMode',e.target.value)}><option value="">기본값 ({form.kind==='postgres'?'인증서 검증':'사용 안 함'})</option><option value="verify-full">인증서·호스트 검증</option><option value="disable">사용 안 함</option></select></label>}</div></section>}
 <section><h3><Terminal size={16}/> SSH · 터미널{form.kind!=='server'&&<small>선택 사항</small>}</h3><div className="field-grid"><label>SSH 주소<input value={form.ssh!.host} onChange={e=>ssh('host',e.target.value)} placeholder={form.kind==='server'?'비우면 기본 주소 사용':'터미널을 열 호스트'}/></label><label>SSH 포트<input type="number" min={1} max={65535} value={form.ssh!.port||''} onChange={e=>ssh('port',Number(e.target.value))} placeholder="22"/></label><label>SSH username<input autoComplete="off" value={form.ssh!.username} onChange={e=>ssh('username',e.target.value)} placeholder="선택 입력"/></label>{secret('sshPassword','SSH password',asset?.hasSshPassword)}<label className="wide">SSH jump · 경유 서버<select value={form.ssh!.jumpId} onChange={e=>ssh('jumpId',e.target.value)}><option value="">직접 연결</option>{assets.filter(a=>a.kind==='server'&&a.id!==asset?.id).map(a=><option key={a.id} value={a.id}>{a.name} · {a.address||'주소 미입력'}</option>)}</select><small>경유할 서버를 먼저 등록하세요. DB·HTTP도 선택한 SSH 서버를 통해 연결합니다.</small></label><label className="wide">PEM / OpenSSH private key<div className="key-actions"><span>{asset?.hasPrivateKey&&form.privateKey===undefined?'키 저장됨 · 기존 키 유지':'키 파일 또는 텍스트 입력'}</span><button className="filter-button" type="button" onClick={()=>file.current?.click()}><Upload size={13}/> 키 파일 선택</button><input ref={file} type="file" hidden onChange={async e=>{const selected=e.target.files?.[0];if(!selected)return;if(selected.size>131072){setError('키 파일은 128KB 이하로 선택하세요.');return}set('privateKey',await selected.text())}}/></div><textarea autoComplete="off" spellCheck={false} className="private-key-input" aria-label="Private key" value={form.privateKey??''} onChange={e=>set('privateKey',e.target.value)} placeholder="-----BEGIN OPENSSH PRIVATE KEY-----" rows={3}/>{asset?.hasPrivateKey&&<button type="button" className="plain-link clear-secret" onClick={()=>set('privateKey','')}>{form.privateKey===''?'저장 시 기존 키 삭제됨':'저장된 키 삭제'}</button>}</label>{secret('passphrase','Key passphrase',asset?.hasPassphrase)}<label className="wide">서버 지문 · SHA256<input value={form.ssh!.fingerprint} onChange={e=>ssh('fingerprint',e.target.value)} placeholder="SHA256:…"/><small>호스트 키를 검증한 연결만 허용합니다. 처음 등록할 때는 비워둘 수 있습니다.</small></label></div>{asset?.id&&<div className="fingerprint-inspect"><button type="button" className="filter-button" disabled={busy} onClick={()=>void inspect()}><ShieldCheck size={14}/> 저장된 주소의 지문 조회</button>{pin&&<div><code>{pin}</code><p>서버 관리자가 제공한 지문과 일치하는지 확인한 후 적용하세요.</p><button type="button" className="filter-button" onClick={()=>{ssh('fingerprint',pin);setPin('')}}>확인한 지문 적용</button></div>}</div>}</section>
 <section><h3>연결 관계</h3><p className="editor-help">이 서버가 사용하는 DB·캐시·다른 서버를 선택하면 이벤트 근거 그래프에 함께 표시됩니다.</p><div className="dependency-options">{assets.filter(a=>a.id!==asset?.id).map(a=><label key={a.id}><input type="checkbox" checked={form.dependencies!.includes(a.id)} onChange={e=>set('dependencies',e.target.checked?[...form.dependencies!,a.id]:form.dependencies!.filter(id=>id!==a.id))}/><span>{a.name}<small>{assetLabels[a.kind]}</small></span></label>)}{!assets.filter(a=>a.id!==asset?.id).length&&<span className="subtle">다른 인프라를 등록한 후 선택할 수 있습니다.</span>}</div></section>
 </div><div className="editor-footer">{error&&<p className="form-error" role="alert">{error}</p>}<span><ShieldCheck size={14}/> 비밀값은 암호화해 저장</span>{asset?.id&&<button type="button" className="plain-link clear-secret" disabled={busy} onClick={()=>void remove()}>{deleteArmed?'등록 삭제 확인':'등록 삭제'}</button>}<button className="filter-button" type="button" onClick={onClose} disabled={busy}>취소</button><button type="submit" className="primary-button" disabled={busy}>{busy?'처리 중…':asset?.id?'변경 저장':'초안 등록'}</button></div></form></DialogContent></Dialog>
}
type Candidate={alias:string;hostname:string;user:string;port:string;proxyJump:string|null;platform:string};
export function SSHCandidates({onClose,onSelect}:{onClose:()=>void;onSelect:(asset:Partial<Asset>)=>void}){
 const [hosts,setHosts]=useState<Candidate[]>([]),[message,setMessage]=useState('후보 확인 중…');
 useEffect(()=>{const controller=new AbortController();fetch('/api/connections',{signal:controller.signal}).then(r=>r.json() as Promise<{hosts:Candidate[];notice:string}>).then(data=>{setHosts(data.hosts||[]);setMessage(data.notice)}).catch(()=>{if(!controller.signal.aborted)setMessage('후보 목록을 읽을 수 없습니다.')});return()=>controller.abort()},[]);
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="connections-dialog"><DialogHeader><DialogTitle>SSH 연결 후보</DialogTitle><DialogDescription>Windows · Linux · macOS 기본 설정에서 발견한 호스트입니다. 선택하면 등록 양식에 채워집니다.</DialogDescription></DialogHeader><p className="dialog-copy">{message}</p><div className="targets-list">{hosts.map(h=><div className="ssh-host" key={h.platform+h.alias}><div><Terminal size={16}/><strong>{h.alias}</strong><span className="tag">{h.platform}</span></div><p>{h.user||'username 미입력'}@{h.hostname}:{h.port||'22'}</p>{h.proxyJump&&<p>경유 설정: {h.proxyJump} · 등록한 서버에서 별도 선택</p>}<button className="filter-button" onClick={()=>onSelect({name:h.alias,kind:'server',address:h.hostname,port:Number(h.port)||22,ssh:{host:'',port:0,username:h.user,jumpId:'',fingerprint:''}})}>등록 정보로 가져오기 <ArrowRight size={13}/></button></div>)}{!hosts.length&&<p className="empty-search">발견된 호스트가 없습니다.</p>}</div><p className="editor-help">개인 키 파일은 자동으로 읽지 않습니다. 등록 후 지문과 인증 정보를 확인하고 연결 여부를 선택하세요.</p></DialogContent></Dialog>
}
