"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,LayoutDashboard,Radio,Settings2,Search,ArrowUpRight,ArrowRight,RefreshCw,Plus,Check,ExternalLink,Clock3,Download,Server,ShieldCheck,Terminal,Plug} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,SidebarInset,useSidebar} from '@/components/ui/sidebar';
import {detectIncidents} from '@/lib/monitoring/rules';
import {infrastructureKind,infrastructureLabels,infrastructureName,type InfrastructureKind} from '@/lib/monitoring/infrastructure';
import type {Snapshot,Target,Incident} from '@/lib/monitoring/types';
import type {Metric} from '@/lib/monitoring/catalog';
import {ConnectionDialog,DetailSheet} from './monitoring-dialogs';
import {InfrastructureDashboard,InfrastructureIcon} from './infrastructure-dashboard';
import {EventWorkspace,IncidentRows} from './event-workspace';
import {shortTime,exportJson} from './monitoring-chart';
import {useMonitoring} from './use-monitoring';

const pages=[{id:'dashboard',title:'대시보드',icon:LayoutDashboard},{id:'events',title:'이벤트',icon:Radio},{id:'settings',title:'환경설정',icon:Settings2}] as const;
type Page=typeof pages[number]['id'];
function NavigationButton(props:React.ComponentProps<typeof SidebarMenuButton>){const {setOpenMobile}=useSidebar();return <SidebarMenuButton {...props} onClick={event=>{props.onClick?.(event);setOpenMobile(false)}}/>}
type Detail={incident:Incident|null;metric:Metric|null;snapshot:Snapshot|null;instance:string};

export default function Dashboard(){
 const [page,setPage]=useState<Page>('dashboard'),[range,setRange]=useState('3600'),[refreshSeconds,setRefreshSeconds]=useState(30),[preferencesReady,setPreferencesReady]=useState(false);
 const [search,setSearch]=useState(''),[kind,setKind]=useState('all'),[connections,setConnections]=useState(false),[connectionTab,setConnectionTab]=useState('sources'),[selectedTarget,setSelectedTarget]=useState<Target|null>(null),[detail,setDetail]=useState<Detail|null>(null);
 const {snapshot,loading,error,reload}=useMonitoring(range,'all',true,refreshSeconds);
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('pulse-display-preferences')||'{}');if([0,30,60].includes(stored.refreshSeconds))setRefreshSeconds(stored.refreshSeconds);if(['900','3600','21600','86400'].includes(stored.range))setRange(stored.range)}catch{}setPreferencesReady(true)},[]);
 useEffect(()=>{if(preferencesReady)try{localStorage.setItem('pulse-display-preferences',JSON.stringify({range,refreshSeconds}))}catch{}},[range,refreshSeconds,preferencesReady]);
 const navigate=useCallback((next:Page)=>{setPage(next);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}))},[]);
 const incidents=useMemo(()=>snapshot?detectIncidents(snapshot):[],[snapshot]);
 const targets=snapshot?.targets||[],up=targets.filter(t=>t.health==='up').length;
 const kinds=Array.from(new Set(targets.map(infrastructureKind)));
 const filtered=targets.filter(t=>(kind==='all'||infrastructureKind(t)===kind)&&`${t.job} ${t.instance} ${infrastructureName(t)} ${infrastructureLabels[infrastructureKind(t)]}`.toLowerCase().includes(search.toLowerCase()));
 const openIncident=(incident:Incident,observation:Snapshot|null=snapshot,instance='all')=>setDetail({incident,metric:null,snapshot:observation,instance});
 const openMetric=(metric:Metric,observation:Snapshot|null,instance:string)=>setDetail({metric,incident:null,snapshot:observation,instance});
 const currentPage=pages.find(p=>p.id===page)!;
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tools=[{name:'read_monitoring_status',title:'운영 상태 읽기',description:'현재 관측된 인프라 수, 연결 상태와 이벤트를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('No arguments allowed');return {page,connected:snapshot?.connected,infrastructureCount:targets.length,events:incidents.map(i=>({title:i.title,severity:i.severity}))}}},{name:'navigate_monitoring_page',title:'모니터링 메뉴 이동',description:'대시보드, 이벤트, 환경설정 중 하나를 엽니다. 서버 작업은 실행하지 않습니다.',inputSchema:{type:'object',properties:{page:{type:'string',enum:pages.map(p=>p.id)}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length!==1||!pages.some(p=>p.id===input.page))throw new Error('Unknown page');navigate(input.page);return {page:input.page}}}];
  for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[snapshot,incidents,targets.length,page,navigate]);
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><button className="brand" onClick={()=>navigate('dashboard')} aria-label="PULSE OPS 대시보드"><span className="brand-mark"><Activity size={23}/></span>PULSE<span className="brand-slash">/</span><span className="brand-ops">OPS</span></button><div className="workspace"><span className="workspace-avatar">P</span><div>My infrastructure<small>{snapshot?.mode==='test'?'Docker test environment':'Observability workspace'}</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{pages.map(p=><SidebarMenuItem key={p.id}><NavigationButton isActive={page===p.id} onClick={()=>navigate(p.id)}><p.icon/><span>{p.title}</span>{p.id==='events'&&incidents.length>0&&<span className="nav-count">{incidents.length}</span>}</NavigationButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-connection"><span className={snapshot?.connected?'status-dot':'muted-dot'}/><span>{snapshot?.connected?'Prometheus 연결됨':'연결 대기'}<small>{targets.length}개 인프라 관측</small></span></div><div className="sidebar-bottom"><span className="operator-avatar">OP</span><div>Operations<small>내 워크스페이스</small></div><ShieldCheck size={16}/></div></SidebarFooter></Sidebar><SidebarInset className="app-main"><header className="topbar"><div><SidebarTrigger/><span className="crumb">Workspace</span><span className="slash">/</span><strong>{currentPage.title}</strong></div><div><span className={'demo-badge '+(snapshot?.connected?'live-badge':'')}>{snapshot?.mode==='test'?'DOCKER TEST':snapshot?.mode==='production'?'PRODUCTION':'NOT CONNECTED'}</span><span className="top-date">Asia / Seoul</span></div></header>
 <main className="content workspace-content"><div className="page-title"><div><div className="eyebrow">{page==='dashboard'?'INFRASTRUCTURE AT A GLANCE':page==='events'?'FROM SIGNALS TO EVENTS':'YOUR WORKSPACE'}</div><h1>{currentPage.title}</h1><p>{page==='dashboard'?'인프라를 선택하고, 필요한 상태만 자세히 살펴보세요.':page==='events'?'어떤 지표가 어떤 조건으로 이벤트가 되는지 확인하세요.':'연결 정보와 화면의 관측 방식을 관리하세요.'}</p></div>{page==='dashboard'&&<button className="primary-button" onClick={()=>{setConnectionTab("sources");setConnections(true)}}><Plus size={16}/> 인프라 연결</button>}</div>
 {page!=='settings'&&<div className="workspace-toolbar"><span className="updated-at"><Clock3 size={13}/>{snapshot?`${shortTime(snapshot.end)} 업데이트`:'지표를 불러오는 중'}<span className="toolbar-dot">·</span>{refreshSeconds?`${refreshSeconds}초 자동 갱신`:'자동 갱신 꺼짐'}</span><div><select className="native-select" aria-label="조회 기간" value={range} onChange={e=>setRange(e.target.value)}><option value="900">최근 15분</option><option value="3600">최근 1시간</option><option value="21600">최근 6시간</option><option value="86400">최근 24시간</option></select><button className="icon-button refresh-button" aria-label="지표 새로고침" onClick={()=>void reload()} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/></button></div></div>}
 {(error||snapshot?.message)&&<div className="status-banner" role="status"><Plug size={17}/><span>{error||snapshot?.message}</span><button onClick={()=>navigate('settings')}>환경설정</button></div>}
 {page==='dashboard'&&<>
 <div className="overview-strip"><div><span className="summary-icon purple"><Server size={18}/></span><div><small>연결된 인프라</small><strong>{targets.length}<span>개</span></strong></div></div><div><span className="summary-icon mint"><Activity size={18}/></span><div><small>수집 응답</small><strong>{up}<span>/ {targets.length}</span></strong></div></div><button onClick={()=>navigate('events')}><span className="summary-icon orange"><Radio size={18}/></span><div><small>현재 이벤트</small><strong>{incidents.length}<span>개</span></strong></div><ArrowUpRight size={16}/></button></div>
 <section className="surface dashboard-events"><div className="surface-heading"><h2><span className="attention-dot"/> 확인이 필요한 이벤트 <span>{incidents.length}</span></h2><button className="plain-link" onClick={()=>navigate('events')}>이벤트 보기 <ArrowRight size={14}/></button></div>{incidents.length?<IncidentRows incidents={incidents} onOpen={i=>openIncident(i)} limit={3}/>:<div className="quiet-state"><Check size={17}/><span>{loading&&!snapshot?'관측 상태를 확인하고 있습니다.':snapshot?.connected?'현재 표시할 이벤트가 없습니다.':'인프라 연결 후 이벤트가 표시됩니다.'}</span></div>}{incidents.length>3&&<button className="more-events" onClick={()=>navigate('events')}>추가 {incidents.length-3}개 이벤트 확인 <ArrowRight size={14}/></button>}</section>
 <section className="infrastructure-section"><div className="section-heading"><h2>내 인프라 <span className="neutral-count">{targets.length}</span></h2><span className="subtle">선택하면 전용 대시보드가 열립니다</span></div><div className="list-toolbar"><div className="category-filters"><button className={kind==='all'?'active':''} onClick={()=>setKind('all')}>전체 <span>{targets.length}</span></button>{kinds.map(k=><button key={k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{infrastructureLabels[k]} <span>{targets.filter(t=>infrastructureKind(t)===k).length}</span></button>)}</div><label className="search-field infra-search"><Search size={15}/><input aria-label="인프라 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="이름 또는 주소 검색"/></label></div>
 <div className="infra-list"><div className="infra-list-head"><span>인프라</span><span>유형</span><span>수집 상태</span><span>최근 수집</span><span/></div>{filtered.map(t=><button className="infra-list-row" key={`${t.job}:${t.instance}`} onClick={()=>setSelectedTarget(t)} aria-label={`${infrastructureName(t)} ${t.instance} 대시보드 열기`}><div className="infra-identity"><InfrastructureIcon kind={infrastructureKind(t)}/><div><strong>{infrastructureName(t)}</strong><small>{t.instance}</small></div></div><span className="infra-type">{infrastructureLabels[infrastructureKind(t)]}</span><span className={`health-label ${!snapshot?.connected?'unknown':t.health==='up'?'healthy':'unhealthy'}`}><i/>{!snapshot?.connected?'확인 불가':t.health==='up'?'수집 중':'수집 실패'}</span><span className="infra-scrape">{t.lastScrape&&Number.isFinite(Date.parse(t.lastScrape))?shortTime(Date.parse(t.lastScrape)/1000):'—'}</span><ArrowUpRight size={16}/></button>)}{!filtered.length&&<div className="infra-empty"><Server size={26}/><strong>{loading&&!snapshot?'인프라를 불러오는 중입니다':targets.length?'검색한 인프라가 없습니다':'연결된 인프라가 없습니다'}</strong><p>{targets.length?'검색어나 분류를 바꿔보세요.':'환경설정에서 수집기와 연결 후보를 확인하세요.'}</p>{!targets.length&&<button className="filter-button" onClick={()=>{setConnectionTab("sources");setConnections(true)}}>연결 안내</button>}</div>}</div><p className="table-explanation">수집 대상별 목록입니다. 수집 중은 지표를 가져올 수 있다는 뜻이며 서비스 정상 여부는 상세 지표에서 확인합니다.</p></section>
 </>}
 {page==='events'&&<EventWorkspace snapshot={snapshot} incidents={incidents} onIncident={i=>openIncident(i)}/>}
 {page==='settings'&&<div className="settings-layout"><section className="surface settings-card"><div className="settings-heading"><Plug size={19}/><div><h2>데이터 소스</h2><p>실제 인프라의 지표를 가져오는 연결입니다.</p></div></div><div className="setting-row"><div><strong>Prometheus</strong><small>{targets.length}개 수집 대상 등록</small></div><span className={`health-label ${snapshot?.connected?'healthy':'unknown'}`}>{snapshot?.connected?'연결됨':'연결 대기'}</span></div><div className="setting-row"><div><strong>Grafana</strong><small>상세 분석용 대시보드</small></div>{snapshot?.grafanaUrl?<a href={snapshot.grafanaUrl+'/d/pulse-ops'} target="_blank" rel="noreferrer" className="plain-link">열기 <ExternalLink size={14}/></a>:<span className="subtle">연결 대기</span>}</div><button className="settings-action" onClick={()=>{setConnectionTab("sources");setConnections(true)}}>연결 상세 및 설정 안내 <ArrowRight size={15}/></button></section>
 <section className="surface settings-card"><div className="settings-heading"><Clock3 size={19}/><div><h2>화면 설정</h2><p>이 브라우저에 저장되는 표시 환경입니다.</p></div></div><label className="setting-row"><div><strong>자동 갱신</strong><small>새 지표를 가져오는 간격</small></div><select className="native-select" aria-label="자동 갱신 간격" value={refreshSeconds} onChange={e=>setRefreshSeconds(Number(e.target.value))}><option value="30">30초</option><option value="60">1분</option><option value="0">사용 안 함</option></select></label><label className="setting-row"><div><strong>조회 기간</strong><small>대시보드와 인프라 상세에 함께 적용</small></div><select className="native-select" aria-label="기본 조회 기간" value={range} onChange={e=>setRange(e.target.value)}><option value="900">최근 15분</option><option value="3600">최근 1시간</option><option value="21600">최근 6시간</option><option value="86400">최근 24시간</option></select></label><div className="setting-row"><div><strong>시간대</strong><small>모든 관측 시각의 표시 기준</small></div><span className="subtle">Asia / Seoul</span></div></section>
 <section className="surface settings-card"><div className="settings-heading"><Terminal size={19}/><div><h2>SSH 연결 후보</h2><p>기본 SSH 설정에서 발견한 호스트를 검토합니다.</p></div></div><p className="settings-note">후보 선택은 이 브라우저에 저장됩니다. 실제 연결이나 원격 설치는 실행되지 않습니다.</p><button className="settings-action" onClick={()=>{setConnectionTab("ssh");setConnections(true)}}>SSH 후보 목록 확인 <ArrowRight size={15}/></button></section>
 <section className="surface settings-card"><div className="settings-heading"><ShieldCheck size={19}/><div><h2>관측 환경</h2><p>{snapshot?.mode==='test'?'Docker 테스트 환경을 사용 중입니다.':'승인된 인프라의 연결 정보를 사용합니다.'}</p></div></div><div className="setting-row"><div><strong>접근 범위</strong><small>현재 워크스페이스의 운영 관측</small></div><span className="subtle">단일 워크스페이스</span></div><button className="settings-action" disabled={!snapshot} onClick={()=>exportJson('pulse-observation.json',{exportedAt:new Date().toISOString(),snapshot,incidents})}><Download size={15}/> 현재 관측 스냅샷 내보내기</button></section></div>}
 <footer className="workspace-footer"><span>PULSE / OPS</span><span>Infrastructure, in focus.</span></footer></main></SidebarInset>
 {selectedTarget&&<InfrastructureDashboard key={`${selectedTarget.job}:${selectedTarget.instance}`} target={selectedTarget} range={range} refreshSeconds={refreshSeconds} onClose={()=>setSelectedTarget(null)} onMetric={openMetric} onIncident={openIncident}/>}
 <DetailSheet incident={detail?.incident||null} metric={detail?.metric||null} snapshot={detail?.snapshot||null} instance={detail?.instance||'all'} onClose={()=>setDetail(null)}/><ConnectionDialog initialTab={connectionTab} open={connections} onChange={setConnections} snapshot={snapshot}/></SidebarProvider>;
}
