"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,LayoutDashboard,Radio,Settings2,Search,ArrowUpRight,ArrowRight,RefreshCw,Plus,Check,Clock3,Server,ShieldCheck,Terminal,Plug,Pencil,Pause,Play} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,SidebarInset,useSidebar} from './ui/sidebar';
import {assetLabels,statusLabels,registeredIncidents,controlRequest,type Asset,scopeSnapshot} from '@/lib/monitoring/assets';
import type {Snapshot,Incident} from '@/lib/monitoring/types';
import type {Metric} from '@/lib/monitoring/catalog';
import {DetailSheet} from './monitoring-dialogs';
import {InfrastructureDashboard,InfrastructureIcon} from './infrastructure-dashboard';
import {AssetEditor,SSHCandidates} from './asset-editor';
import {AssetTerminal} from './asset-terminal';
import {EventWorkspace,IncidentRows} from './event-workspace';
import {shortTime} from './monitoring-chart';
import {useMonitoring} from './use-monitoring';
const pages=[{id:'dashboard',title:'대시보드',icon:LayoutDashboard},{id:'events',title:'이벤트',icon:Radio},{id:'settings',title:'환경설정',icon:Settings2}] as const;
type Page=typeof pages[number]['id'];
type Detail={incident:Incident|null;metric:Metric|null;snapshot:Snapshot|null;instance:string};
function Nav(props:React.ComponentProps<typeof SidebarMenuButton>){const {setOpenMobile}=useSidebar();return <SidebarMenuButton {...props} onClick={e=>{props.onClick?.(e);setOpenMobile(false)}}/>}
export default function Dashboard(){
 const [page,setPage]=useState<Page>('dashboard'),[range,setRange]=useState('3600'),[refreshSeconds,setRefreshSeconds]=useState(30),[ready,setReady]=useState(false),[search,setSearch]=useState(''),[kind,setKind]=useState('all');
 const [editor,setEditor]=useState<Partial<Asset>|null>(null),[candidates,setCandidates]=useState(false),[selected,setSelected]=useState<string|null>(null),[terminal,setTerminal]=useState<Asset|null>(null),[detail,setDetail]=useState<Detail|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState<string|null>(null);
 const {snapshot,loading,error,reload}=useMonitoring(range,'all',true,refreshSeconds);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('pulse-display-preferences')||'{}');if([0,30,60].includes(p.refreshSeconds))setRefreshSeconds(p.refreshSeconds);if(['900','3600','21600','86400'].includes(p.range))setRange(p.range)}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('pulse-display-preferences',JSON.stringify({range,refreshSeconds}))}catch{}},[range,refreshSeconds,ready]);
 const navigate=useCallback((next:Page)=>{setPage(next);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}))},[]);
 const incidents=useMemo(()=>snapshot?registeredIncidents(snapshot):[],[snapshot]);
 const assets=snapshot?.assets||[],active=assets.filter(a=>a.status==='connected').length,current=pages.find(p=>p.id===page)!,selectedAsset=assets.find(a=>a.id===selected);
 const filtered=assets.filter(a=>(kind==='all'||a.kind===kind)&&`${a.name} ${a.address} ${a.environment}`.toLowerCase().includes(search.toLowerCase()));
 const openIncident=(incident:Incident)=>setDetail({incident,metric:null,snapshot:snapshot&&incident.assetId?scopeSnapshot(snapshot,incident.assetId):snapshot,instance:incident.assetId||'all'});
 const edit=(a:Partial<Asset>)=>{setSelected(null);setEditor(a);setNotice('')};
 const action=async(a:Asset,verb:'connect'|'pause')=>{setBusy(a.id);setNotice('');try{await controlRequest(`assets/${a.id}/${verb}`,'POST')}catch(e){setNotice((e as Error).message)}finally{await reload();setBusy(null)}};
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  for(const tool of [{name:'read_monitoring_status',title:'등록 인프라 상태 읽기',description:'등록한 인프라의 연결 상태와 이벤트를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({page,connected:snapshot?.connected,infrastructureCount:assets.length,events:incidents.map(i=>({title:i.title,scope:i.scope,severity:i.severity}))})},{name:'navigate_monitoring_page',title:'모니터링 메뉴 이동',description:'대시보드, 이벤트, 환경설정 화면을 엽니다.',inputSchema:{type:'object',properties:{page:{type:'string',enum:pages.map(p=>p.id)}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length!==1||!pages.some(p=>p.id===input.page))throw new Error('Unknown page');navigate(input.page);return {page:input.page}}}])try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[snapshot,incidents,assets.length,page,navigate]);
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader><button className="brand" onClick={()=>navigate('dashboard')}><span className="brand-mark"><Activity size={23}/></span>PULSE<span className="brand-slash">/</span><span className="brand-ops">OPS</span></button><div className="workspace"><span className="workspace-avatar">P</span><div>My infrastructure<small>{snapshot?.mode==='test'?'Docker test environment':'Infrastructure workspace'}</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu>{pages.map(p=><SidebarMenuItem key={p.id}><Nav isActive={page===p.id} onClick={()=>navigate(p.id)}><p.icon/><span>{p.title}</span>{p.id==='events'&&incidents.length>0&&<span className="nav-count">{incidents.length}</span>}</Nav></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="sidebar-connection"><span className={snapshot?.connected?'status-dot':'muted-dot'}/><span>{snapshot?.connected?'인프라 관리 연결됨':'관리 서비스 연결 대기'}<small>{assets.length}개 등록 · {active}개 수집 중</small></span></div><div className="sidebar-bottom"><span className="operator-avatar">OP</span><div>Operations<small>내 워크스페이스</small></div><ShieldCheck size={16}/></div></SidebarFooter></Sidebar><SidebarInset className="app-main"><header className="topbar"><div><SidebarTrigger/><span className="crumb">Workspace</span><span className="slash">/</span><strong>{current.title}</strong></div><div><span className={'demo-badge '+(snapshot?.connected?'live-badge':'')}>{snapshot?.mode==='test'?'DOCKER TEST':snapshot?.mode==='production'?'PRODUCTION':'NOT CONNECTED'}</span><span className="top-date">Asia / Seoul</span></div></header>
 <main className="content workspace-content"><div className="page-title"><div><div className="eyebrow">{page==='dashboard'?'YOUR INFRASTRUCTURE, IN FOCUS':page==='events'?'FROM SIGNALS TO EVENTS':'YOUR WORKSPACE'}</div><h1>{current.title}</h1><p>{page==='dashboard'?'등록한 인프라의 상태를 확인하고, 필요한 곳에 집중하세요.':page==='events'?'규칙을 펼쳐 발생 조건과 연결된 인프라의 근거를 확인하세요.':'인프라 연결과 관측 환경을 관리하세요.'}</p></div><button className="primary-button" onClick={()=>edit({})}><Plus size={16}/> 인프라 등록</button></div>
 {page!=='settings'&&<div className="workspace-toolbar"><span className="updated-at"><Clock3 size={13}/>{snapshot?`${shortTime(snapshot.end)} 업데이트`:'관측 상태 확인 중'}<span className="toolbar-dot">·</span>{refreshSeconds?`${refreshSeconds}초 화면 갱신`:'자동 갱신 꺼짐'}</span><div><select className="native-select" aria-label="조회 기간" value={range} onChange={e=>setRange(e.target.value)}><option value="900">최근 15분</option><option value="3600">최근 1시간</option><option value="21600">최근 6시간</option><option value="86400">최근 24시간</option></select><button className="icon-button" aria-label="지표 새로고침" disabled={loading} onClick={()=>void reload()}><RefreshCw size={15} className={loading?'spin':''}/></button></div></div>}
 {(notice||error||snapshot?.message)&&<div className="status-banner" role="status"><Plug size={17}/><span>{notice||error||snapshot?.message}</span>{notice&&<button onClick={()=>setNotice('')}>닫기</button>}</div>}
 {page==='dashboard'&&<><div className="overview-strip"><div><span className="summary-icon purple"><Server size={18}/></span><div><small>등록한 인프라</small><strong>{assets.length}<span>개</span></strong></div></div><div><span className="summary-icon mint"><Activity size={18}/></span><div><small>수집 중</small><strong>{active}<span>/ {assets.length}</span></strong></div></div><button onClick={()=>navigate('events')}><span className="summary-icon orange"><Radio size={18}/></span><div><small>확인할 이벤트</small><strong>{incidents.length}<span>개</span></strong></div><ArrowUpRight size={16}/></button></div>
 <section className="surface dashboard-events"><div className="surface-heading"><h2><span className="attention-dot"/> 확인이 필요한 이벤트 <span>{incidents.length}</span></h2><button className="plain-link" onClick={()=>navigate('events')}>이벤트 보기 <ArrowRight size={14}/></button></div>{incidents.length?<IncidentRows incidents={incidents} onOpen={openIncident} limit={3}/>:<div className="quiet-state"><Check size={17}/><span>{snapshot?.connected?'현재 표시할 이벤트가 없습니다. 표본이 쌓이면 조건을 평가합니다.':'인프라를 연결하면 상태를 확인할 수 있습니다.'}</span></div>}{incidents.length>3&&<button className="more-events" onClick={()=>navigate('events')}>추가 {incidents.length-3}개 이벤트 확인 <ArrowRight size={14}/></button>}</section>
 <section className="infrastructure-section"><div className="section-heading"><h2>내 인프라 <span className="neutral-count">{assets.length}</span></h2><button className="plain-link" onClick={()=>setCandidates(true)}><Terminal size={14}/> SSH 후보 가져오기</button></div><div className="list-toolbar"><div className="category-filters"><button className={kind==='all'?'active':''} onClick={()=>setKind('all')}>전체 <span>{assets.length}</span></button>{Object.entries(assetLabels).filter(([k])=>assets.some(a=>a.kind===k)).map(([k,label])=><button key={k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{label} <span>{assets.filter(a=>a.kind===k).length}</span></button>)}</div><label className="search-field infra-search"><Search size={15}/><input aria-label="인프라 검색" value={search} onChange={e=>setSearch(e.target.value)} placeholder="이름, 주소, 환경 검색"/></label></div>
 <div className="registered-list"><div className="registered-head"><span>인프라 · 주소</span><span>수집 상태</span><span>최근 관측</span><span>연결 관리</span></div>{filtered.map(a=><div className="registered-row" key={a.id}><button className="registered-identity" onClick={()=>setSelected(a.id)} aria-label={`${a.name} 대시보드 열기`}><InfrastructureIcon kind={a.kind}/><span><strong>{a.name}<ArrowUpRight size={13}/></strong><small>{a.address||'주소 미입력'}{a.port?`:${a.port}`:''}</small><em>{assetLabels[a.kind]} · {a.environment||'환경 미지정'}</em></span></button><span className={`health-label ${a.status==='connected'?'healthy':a.status==='error'?'unhealthy':'unknown'}`}><i/>{statusLabels[a.status]||a.status}</span><span className="infra-scrape">{a.lastSeen?shortTime(Date.parse(a.lastSeen)/1000):'—'}</span><div className="asset-actions"><button className="icon-button" aria-label={`${a.name} 연결 정보 수정`} title="연결 정보 수정" onClick={()=>edit(a)}><Pencil size={15}/></button><button className="icon-button" aria-label={`${a.name} 터미널 열기`} title="SSH 터미널" onClick={()=>setTerminal(a)}><Terminal size={15}/></button><button className="asset-connect" disabled={busy===a.id} onClick={()=>void action(a,a.enabled?'pause':'connect')}>{busy===a.id?<RefreshCw size={13} className="spin"/>:a.enabled?<Pause size={13}/>:<Play size={13}/>} {a.enabled?'일시정지':'연결 시작'}</button></div></div>)}{!filtered.length&&<div className="infra-empty"><Server size={27}/><strong>{assets.length?'검색한 인프라가 없습니다':'첫 인프라를 등록하세요'}</strong><p>{assets.length?'검색어나 분류를 바꿔보세요.':'서버·DB·캐시의 연결 정보를 직접 등록하고 관리합니다.'}</p><button className="filter-button" onClick={()=>edit({})}><Plus size={14}/> 인프라 등록</button></div>}</div><p className="table-explanation">직접 등록한 인프라만 표시합니다. 연결 정보를 저장하면 초안 상태가 되며, 연결 시작을 선택한 대상만 수집합니다.</p></section></>}
 {page==='events'&&<EventWorkspace snapshot={snapshot} incidents={incidents} onIncident={openIncident}/>}
 {page==='settings'&&<div className="settings-layout"><section className="surface settings-card"><div className="settings-heading"><Plug size={19}/><div><h2>인프라 연결</h2><p>주소·인증·경유 경로는 각 등록 정보에서 관리합니다.</p></div></div><div className="setting-row"><div><strong>등록 인프라</strong><small>서버 · 애플리케이션 · DB · 캐시 · HTTP</small></div><span>{assets.length}개</span></div><button className="settings-action" onClick={()=>navigate('dashboard')}>인프라 목록에서 관리 <ArrowRight size={15}/></button><button className="settings-action" onClick={()=>setCandidates(true)}><Terminal size={15}/> 기본 SSH 설정에서 후보 가져오기</button></section><section className="surface settings-card"><div className="settings-heading"><Clock3 size={19}/><div><h2>화면 설정</h2><p>이 브라우저에 저장되는 표시 환경입니다.</p></div></div><label className="setting-row"><div><strong>자동 갱신</strong><small>화면의 최신 관측값 갱신</small></div><select className="native-select" value={refreshSeconds} onChange={e=>setRefreshSeconds(Number(e.target.value))}><option value="30">30초</option><option value="60">1분</option><option value="0">사용 안 함</option></select></label><div className="setting-row"><div><strong>시간대</strong><small>모든 관측 시각</small></div><span className="subtle">Asia / Seoul</span></div><div className="setting-row"><div><strong>관측 보존</strong><small>현재 화면은 최대 24시간 조회</small></div><span className="subtle">15일</span></div></section><section className="surface settings-card"><div className="settings-heading"><ShieldCheck size={19}/><div><h2>접근과 인증</h2><p>비밀값은 서버에서 암호화해 보관합니다.</p></div></div><p className="settings-note">SSH는 저장한 서버 지문을 검증합니다. 연결과 터미널 세션의 시작·종료는 감사 이력에 남습니다. 현재 접근 범위는 단일 운영 워크스페이스입니다.</p><AuditList assets={assets}/></section><section className="surface settings-card"><div className="settings-heading"><Activity size={19}/><div><h2>지표 수집</h2><p>각 인프라에 맞는 방식으로 직접 수집합니다.</p></div></div><p className="settings-note">서버는 SSH 리소스 조회, PostgreSQL·Redis는 읽기 전용 상태 조회, 웹은 HTTP 검사로 확인합니다. 애플리케이션 P99·쿠키 만료·런타임 지표는 등록한 계측 URL에서 가져옵니다.</p><p className="settings-note">Prometheus와 Grafana는 필수 연결 대상이 아닙니다. 설치된 테스트 도구는 별도 분석에 사용할 수 있습니다.</p></section></div>}
 <footer className="workspace-footer"><span>PULSE / OPS</span><span>Infrastructure, in focus.</span></footer></main></SidebarInset>
 {selectedAsset&&<InfrastructureDashboard asset={selectedAsset} snapshot={snapshot} onClose={()=>setSelected(null)} onEdit={()=>edit(selectedAsset)} onTerminal={()=>{setSelected(null);setTerminal(selectedAsset)}} onAction={()=>void action(selectedAsset,selectedAsset.enabled?'pause':'connect')} onMetric={(metric,observation)=>setDetail({metric,incident:null,snapshot:observation,instance:selectedAsset.id})} onIncident={openIncident}/>}
 {editor&&<AssetEditor asset={editor} assets={assets} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);void reload()}}/>}{candidates&&<SSHCandidates onClose={()=>setCandidates(false)} onSelect={a=>{setCandidates(false);edit(a)}}/>}{terminal&&<AssetTerminal asset={terminal} onClose={()=>setTerminal(null)}/>}
 <DetailSheet incident={detail?.incident||null} metric={detail?.metric||null} snapshot={detail?.snapshot||null} instance={detail?.instance||'all'} onClose={()=>setDetail(null)}/></SidebarProvider>
}
function AuditList({assets}:{assets:Asset[]}){
 const [rows,setRows]=useState<{assetId:string;action:string;status:string;at:string}[]>([]),[error,setError]=useState('');
 useEffect(()=>{let disposed=false;controlRequest<typeof rows>('audit').then(data=>{if(!disposed)setRows(data)}).catch(()=>{if(!disposed)setError('감사 이력을 불러오지 못했습니다.')});return()=>{disposed=true}},[]);
 return <div className="audit-list">{rows.slice(0,6).map((r,i)=><div key={i}><span>{assets.find(a=>a.id===r.assetId)?.name||'삭제된 인프라'}<small>{r.action} · {r.status}</small></span><time>{shortTime(Date.parse(r.at)/1000)}</time></div>)}{(!rows.length||error)&&<p>{error||'연결 활동이 기록되면 표시합니다.'}</p>}</div>
}
