"use client";
import {useState} from 'react';
import {Server,Database,Layers,Globe,Terminal,Pencil,Radio,ArrowRight,Activity} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {metrics,metricById,type Metric} from '@/lib/monitoring/catalog';
import {assetLabels,statusLabels,databaseProfiles,scopeSnapshot,registeredIncidents,type Asset,type AssetKind} from '@/lib/monitoring/assets';
import {formatNumber} from '@/lib/monitoring/rules';
import type {Snapshot,Incident} from '@/lib/monitoring/types';
import {MetricPanel,stateLabel} from './monitoring-chart';
import {EvidenceCharts} from './evidence-charts';
export function InfrastructureIcon({kind}:{kind:AssetKind}){const Icon={server:Server,application:Activity,postgres:Database,mysql:Database,mariadb:Database,oracle:Database,redis:Layers,http:Globe}[kind];return <span className={`infra-icon ${kind}`}><Icon size={20}/></span>}
const profiles:Record<AssetKind,string[]>={server:['node-cpu','memory-host','load','disk','disk-free','network-in','network-out','uptime'],application:['requests','p99','p97','p95','p50','errors','cpu','memory','db-latency','pool-wait','pool-active','cookie-expiry','queue','cache-hit'],postgres:databaseProfiles.postgres,mysql:databaseProfiles.mysql,mariadb:databaseProfiles.mariadb,oracle:databaseProfiles.oracle,redis:['redis-up','redis-probe','redis-memory','redis-hit','redis-blocked','redis-expired','redis-evictions'],http:['probe','probe-latency','http-status','tls-expiry']};
export function InfrastructureDashboard({asset,snapshot,onClose,onEdit,onTerminal,onAction,onMetric,onIncident}:{asset:Asset;snapshot:Snapshot|null;onClose:()=>void;onEdit:()=>void;onTerminal:()=>void;onAction:()=>void;onMetric:(m:Metric,s:Snapshot|null)=>void;onIncident:(i:Incident)=>void}){
 const [view,setView]=useState('overview'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const scoped=snapshot?scopeSnapshot(snapshot,asset.id):null,results=new Map(scoped?.metrics.map(m=>[m.id,m])||[]),incidents=scoped?registeredIncidents(scoped):[];
 const primary=profiles[asset.kind].slice(0,4).map(id=>metricById.get(id)!),profile=metrics.filter(m=>profiles[asset.kind].includes(m.id)||results.get(m.id)?.series.length);
 const filtered=profile.filter(m=>`${m.title} ${m.id}`.toLowerCase().includes(search.toLowerCase()));
 return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="infra-dialog"><DialogHeader className="infra-modal-header"><div className="infra-heading"><InfrastructureIcon kind={asset.kind}/><div><div className="eyebrow">{assetLabels[asset.kind]} DASHBOARD</div><DialogTitle>{asset.name}</DialogTitle></div></div><DialogDescription><span className="mono">{asset.address||'주소 미입력'}</span><span className={`health-label ${asset.status==='connected'?'healthy':'unknown'}`}>{statusLabels[asset.status]}</span></DialogDescription></DialogHeader><div className="infra-modal-body"><div className="modal-context"><span>{asset.environment||'환경 미지정'} · 이 인프라 기준</span><div className="modal-actions"><button className="filter-button" onClick={onEdit}><Pencil size={13}/> 연결 정보</button><button className="filter-button" onClick={onTerminal}><Terminal size={14}/> 터미널</button><button className="filter-button" onClick={onAction}>{asset.enabled?'수집 일시정지':'연결 시작'}</button></div></div>{asset.message&&(asset.status!=='connected'||results.get('db-monitoring-ready')?.latest===0)&&<p className="status-banner">{asset.message}</p>}<div className="infra-kpis">{primary.map(m=>{const result=results.get(m.id);return <button key={m.id} onClick={()=>onMetric(m,scoped)}><span>{m.title}</span><strong>{result?.latest!=null?(m.unit==='0/1'?(result.latest===1?'연결됨':'연결 실패'):formatNumber(result.latest)):'—'}{m.unit!=='0/1'&&<small>{m.unit}</small>}</strong><small className={result?.state==='ok'?'mint':''}>{stateLabel[result?.state||'missing']}</small></button>})}</div>
 {!!incidents.length&&<div className="asset-incidents"><div><Radio size={15}/> 이 인프라의 이벤트 <span>{incidents.length}</span></div>{incidents.slice(0,4).map(i=><button key={i.id} onClick={()=>onIncident(i)}><span className={'severity-dot '+i.severity}/><strong>{i.title}</strong><span>{i.value} {i.unit}</span><ArrowRight size={14}/></button>)}</div>}
 <div className="modal-viewbar"><div className="category-filters"><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}>연결 관계 · 핵심 그래프</button><button className={view==='metrics'?'active':''} onClick={()=>setView('metrics')}>개별 지표 {profile.length}</button></div></div>
 {view==='overview'?<EvidenceCharts key={asset.id} snapshot={snapshot} metricIds={primary.map(m=>m.id)} initialAssetId={asset.id}/>:<><label className="search-field modal-search"><input aria-label="인프라 지표 검색" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="지표 검색"/></label><div className="chart-grid asset-charts">{filtered.slice(page*6,(page+1)*6).map(m=><MetricPanel key={m.id} metric={m} result={results.get(m.id)} onOpen={()=>onMetric(m,scoped)}/>)}</div><div className="pagination"><span>{filtered.length}개 지표</span><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><button disabled={(page+1)*6>=filtered.length} onClick={()=>setPage(p=>p+1)}>다음</button></div></>}
 <p className="modal-footnote">DB 변화율은 두 표본, 애플리케이션 백분위는 5분 표본이 필요합니다. 권한이나 지원 범위 밖의 지표는 미관측입니다.</p></div></DialogContent></Dialog>
}
