"use client";
import {useMemo} from 'react';
import {ArrowUpRight,ChartNoAxesCombined} from 'lucide-react';
import {AreaChart,Area,ResponsiveContainer,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from 'recharts';
import type {Metric} from '@/lib/monitoring/catalog';
import type {MetricResult} from '@/lib/monitoring/types';
import {formatNumber} from '@/lib/monitoring/rules';
export const stateLabel={ok:'관측 중',missing:'미관측',error:'조회 오류',stale:'관측 지연'};
export const shortTime=(v:number)=>new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Seoul'}).format(v*1000);
export const fullTime=(v:string|number)=>new Date(typeof v==='number'?v*1000:v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false});
export function exportJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
const colors=['#b5a1ff','#66d6b7','#75aff8','#edb773','#f187a1','#8cb9af','#d8a1ff','#aad877'];
export function MiniPlot({result,color}:{result?:MetricResult;color:string}){const points=result?.series[0]?.points||[];if(!points.some(p=>p.value!==null))return <div className="mini-empty"/>;return <div className="mini-plot" aria-hidden="true"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={points}><Area dataKey="value" stroke={color} strokeWidth={1.6} fill={color} fillOpacity={.08} isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div>}
export function Plot({result,metric,compact=false}:{result?:MetricResult;metric:Metric;compact?:boolean}){
 const series=result?.series||[];
 const data=useMemo(()=>{const rows=new Map<number,Record<string,number|null>>();series.forEach((s,i)=>s.points.forEach(p=>{if(!rows.has(p.time))rows.set(p.time,{time:p.time});rows.get(p.time)![`v${i}`]=p.value;}));return [...rows.values()].sort((a,b)=>Number(a.time)-Number(b.time));},[series]);
 if(!series.some(s=>s.points.some(p=>p.value!==null)))return <div className={'chart-empty '+(compact?'compact':'')}><ChartNoAxesCombined size={25}/><span>{result?.state==='error'?'수집기에서 조회하지 못했습니다':'아직 관측된 값이 없습니다'}</span><small>{metric.source} 계측 필요</small></div>;
 return <div className={'chart '+(compact?'compact':'')}><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{top:8,right:8,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#2b2c36" strokeDasharray="3 5"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={shortTime} tick={{fill:'#9298ac',fontSize:12}} tickLine={false} axisLine={false} minTickGap={45}/><YAxis width={52} tick={{fill:'#9298ac',fontSize:12}} tickLine={false} axisLine={false} tickFormatter={v=>Math.abs(v)>9999?(v/1000).toFixed(0)+'k':formatNumber(v)}/><Tooltip labelFormatter={v=>fullTime(Number(v))} formatter={v=>[v===null?'미관측':`${formatNumber(Number(v))} ${metric.unit}`]} contentStyle={{background:'#232530',border:'1px solid #46404e',borderRadius:8,fontSize:12}}/>{metric.warning!==undefined&&<ReferenceLine y={metric.warning} stroke="#d2a872" strokeDasharray="4 5" ifOverflow="extendDomain"/>}{series.map((s,i)=><Area key={i} dataKey={`v${i}`} name={Object.values(s.labels).join(' · ')||metric.title} stroke={colors[i%colors.length]} strokeWidth={1.8} fill={colors[i%colors.length]} fillOpacity={i===0?.065:0} connectNulls={false} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer></div>
}
export function MetricPanel({metric,result,onOpen}:{metric:Metric;result?:MetricResult;onOpen:()=>void}){
 const warning=result?.latest!=null&&metric.warning!==undefined&&(metric.direction==='below'?result.latest<metric.warning:result.latest>metric.warning);
 return <article id={`metric-${metric.id}`} className="panel metric-panel"><div className="panel-title"><div><h3>{metric.title}</h3><span className="metric-source">{metric.source}</span></div><button className="icon-button" aria-label={`${metric.title} 상세`} onClick={onOpen}><ArrowUpRight size={16}/></button></div><div className="metric-reading"><strong className={warning?'orange':''}>{result?.latest!=null?formatNumber(result.latest):'—'}</strong><span>{metric.unit}</span><span className={'metric-status '+(result?.state==='ok'?'mint':'')}>{stateLabel[result?.state||'missing']}</span></div><Plot metric={metric} result={result}/><div className="metric-caption">{metric.warning!==undefined?<><span className="threshold-dash"/>검토 기준 {metric.direction==='below'?'<':'>'} {metric.warning} {metric.unit}</>:<span>관측값 · Asia/Seoul</span>}<span>{result?.truncated?'최대 8개 시계열':'5분 변화율 / 원시 게이지'}</span></div></article>
}
